package dev.nexus.service.db;

import dev.nexus.service.jooq.t1.tables.Scratch;
import dev.nexus.service.jooq.t1.tables.records.ScratchRecord;
import org.jooq.DSLContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static dev.nexus.service.jooq.t1.Tables.SCRATCH;
import static org.jooq.impl.DSL.*;

/**
 * RDR-152 bead nexus-gmiaf.13 — jOOQ-based T1 scratch repository.
 *
 * <p>Stores ephemeral session working memory in {@code t1.scratch} (UNLOGGED).
 *
 * <p>Isolation model (two levels):
 * <ol>
 *   <li>Tenant-level: Row-Level Security policy {@code tenant_isolation} filters by
 *       {@code tenant_id = current_setting('nexus.t1_tenant', true)}. Stamped by
 *       {@link TenantScope#withTenant} with GUC name {@code nexus.t1_tenant}.</li>
 *   <li>Session-level: {@code session_id} column filter in every WHERE clause.
 *       The caller passes session_id from the {@code X-Nexus-T1-Session} header;
 *       session rows are invisible to other sessions within the same tenant.</li>
 * </ol>
 *
 * <p>Search semantics (BEHAVIOR CHANGE from ChromaDB T1):
 * T1 scratch search was semantic/vector (ChromaDB ONNX cosine similarity).
 * This PG backend has no pgvector; search is FTS via {@code tsvector}.
 * Query: OR of {@code plainto_tsquery('english', q)} and
 * {@code plainto_tsquery('simple', q)} — prose tokens via English stemmer AND
 * identifier/tag tokens via simple config. Same OR-query pattern as T2 memory
 * and plans (RDR-152 152-FTS-tokenizer-DECISION). Rankings use {@code ts_rank}.
 * Ranking is BM25-like, not cosine; very short or exact-identifier queries still
 * work via the simple config branch.
 *
 * <p>Session lifecycle:
 * <ul>
 *   <li>{@link #closeSession} — deletes all rows for (tenant, session_id).
 *       Called from MCP lifespan on exit (promptness guarantee).</li>
 *   <li>{@link #sweepExpired} — deletes rows older than the given cutoff.
 *       Called periodically by a service timer (crash-safety backstop).</li>
 * </ul>
 *
 * <p>No ETL: scratch is ephemeral. Existing ChromaDB scratch is SKIPPED.
 */
public final class ScratchRepository {

    private static final Logger log = LoggerFactory.getLogger(ScratchRepository.class);

    /**
     * GUC name for T1 tenant isolation.
     * Distinct from {@code nexus.tenant} (T2) to avoid conflating contexts
     * when T1 and T2 connections share a pool or sequential transactions.
     */
    public static final String T1_TENANT_GUC = "nexus.t1_tenant";

    private final TenantScope tenantScope;

    public ScratchRepository(TenantScope tenantScope) {
        this.tenantScope = tenantScope;
    }

    // ── Write ──────────────────────────────────────────────────────────────────

    /**
     * Insert a scratch entry. Returns the {@code id}.
     *
     * @param tenant    tenant identifier (stamped into nexus.t1_tenant GUC via TenantScope)
     * @param sessionId session identifier (column filter; NOT a GUC)
     * @param id        UUID string (generated by caller)
     * @param content   entry content (required)
     * @param tags      comma-separated tags (may be null)
     * @param agent     subagent attribution (may be null)
     * @param flagged   whether flagged for SessionEnd T2 flush
     * @param flushProject T2 destination project (may be null)
     * @param flushTitle   T2 destination title (may be null)
     */
    public String put(
            String tenant, String sessionId,
            String id, String content, String tags, String agent,
            boolean flagged, String flushProject, String flushTitle) {
        tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            dsl.insertInto(SCRATCH)
               .set(SCRATCH.ID, id)
               .set(SCRATCH.TENANT_ID, tenant)
               .set(SCRATCH.SESSION_ID, sessionId)
               .set(SCRATCH.CONTENT, content)
               .set(SCRATCH.TAGS, tags)
               .set(SCRATCH.AGENT, agent)
               .set(SCRATCH.FLAGGED, flagged)
               .set(SCRATCH.FLUSH_PROJECT, flushProject)
               .set(SCRATCH.FLUSH_TITLE, flushTitle)
               .set(SCRATCH.ACCESS_COUNT, 0)
               .set(SCRATCH.TS, OffsetDateTime.now(ZoneOffset.UTC))
               .execute();
            return null;
        });
        return id;
    }

    /**
     * Get a scratch entry by id, scoped to (tenant, session_id).
     * Also increments {@code access_count} and updates {@code last_accessed}.
     * Returns empty map when not found or not owned by this session.
     */
    public Map<String, Object> get(String tenant, String sessionId, String id) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            ScratchRecord rec = dsl.selectFrom(SCRATCH)
                .where(SCRATCH.ID.eq(id).and(SCRATCH.SESSION_ID.eq(sessionId)))
                .fetchOne();
            if (rec == null) return Map.of();
            // Increment access_count atomically, then return new value in response
            int newCount = rec.getAccessCount() + 1;
            OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
            dsl.update(SCRATCH)
               .set(SCRATCH.ACCESS_COUNT, newCount)
               .set(SCRATCH.LAST_ACCESSED, now)
               .where(SCRATCH.ID.eq(id))
               .execute();
            // Return the post-increment value so the caller sees the updated access_count
            rec.setAccessCount(newCount);
            rec.setLastAccessed(now);
            return toRow(rec);
        });
    }

    /**
     * FTS search over content + tags, scoped to (tenant, session_id).
     * Returns up to {@code limit} results ordered by ts_rank descending.
     *
     * <p>BEHAVIOR CHANGE: was vector/cosine (ChromaDB ONNX), now FTS.
     * OR-query: english plainto_tsquery (prose stemming) + simple (identifiers/tags).
     */
    public List<Map<String, Object>> search(
            String tenant, String sessionId, String query, int limit) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            var englishQuery = plaintoTsquery(inline("english"), inline(query));
            var simpleQuery  = plaintoTsquery(inline("simple"),  inline(query));
            var ftsVector    = field("fts_vector", Object.class);
            // Conditions: use condition() to wrap raw SQL boolean expressions
            var englishMatch = condition("{0} @@ {1}", ftsVector, englishQuery);
            var simpleMatch  = condition("{0} @@ {1}", ftsVector, simpleQuery);
            var tsCondition  = ftsVector.isNotNull()
                .and(SCRATCH.SESSION_ID.eq(sessionId))
                .and(englishMatch.or(simpleMatch));
            var rankField = field("ts_rank(fts_vector, {0} || {1})",
                Double.class, englishQuery, simpleQuery);

            List<ScratchRecord> recs = dsl.selectFrom(SCRATCH)
                .where(tsCondition)
                .orderBy(rankField.desc())
                .limit(limit)
                .fetch();

            // Batch update access_count
            OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
            List<String> ids = recs.stream().map(ScratchRecord::getId).toList();
            if (!ids.isEmpty()) {
                dsl.update(SCRATCH)
                   .set(SCRATCH.ACCESS_COUNT, SCRATCH.ACCESS_COUNT.add(1))
                   .set(SCRATCH.LAST_ACCESSED, now)
                   .where(SCRATCH.ID.in(ids))
                   .execute();
            }

            return recs.stream().map(this::toRow).toList();
        });
    }

    /**
     * List all entries for (tenant, session_id).
     */
    public List<Map<String, Object>> listEntries(String tenant, String sessionId) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            return dsl.selectFrom(SCRATCH)
                .where(SCRATCH.SESSION_ID.eq(sessionId))
                .orderBy(SCRATCH.TS.desc())
                .fetch()
                .stream().map(this::toRow).toList();
        });
    }

    /**
     * List flagged entries for (tenant, session_id).
     */
    public List<Map<String, Object>> flaggedEntries(String tenant, String sessionId) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            return dsl.selectFrom(SCRATCH)
                .where(SCRATCH.SESSION_ID.eq(sessionId).and(SCRATCH.FLAGGED.isTrue()))
                .orderBy(SCRATCH.TS.desc())
                .fetch()
                .stream().map(this::toRow).toList();
        });
    }

    /**
     * Flag an entry for SessionEnd T2 flush.
     * Returns false when not found or not owned by this session.
     */
    public boolean flag(
            String tenant, String sessionId, String id,
            String flushProject, String flushTitle) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            int updated = dsl.update(SCRATCH)
                .set(SCRATCH.FLAGGED, true)
                .set(SCRATCH.FLUSH_PROJECT, flushProject)
                .set(SCRATCH.FLUSH_TITLE, flushTitle)
                .where(SCRATCH.ID.eq(id).and(SCRATCH.SESSION_ID.eq(sessionId)))
                .execute();
            return updated > 0;
        });
    }

    /**
     * Unflag an entry (remove SessionEnd flush marking).
     * Returns false when not found or not owned by this session.
     */
    public boolean unflag(String tenant, String sessionId, String id) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            int updated = dsl.update(SCRATCH)
                .set(SCRATCH.FLAGGED, false)
                .set(SCRATCH.FLUSH_PROJECT, (String) null)
                .set(SCRATCH.FLUSH_TITLE, (String) null)
                .where(SCRATCH.ID.eq(id).and(SCRATCH.SESSION_ID.eq(sessionId)))
                .execute();
            return updated > 0;
        });
    }

    /**
     * Delete a scratch entry by id.
     * Returns false when not found or not owned by this session.
     */
    public boolean delete(String tenant, String sessionId, String id) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            int deleted = dsl.deleteFrom(SCRATCH)
                .where(SCRATCH.ID.eq(id).and(SCRATCH.SESSION_ID.eq(sessionId)))
                .execute();
            return deleted > 0;
        });
    }

    /**
     * Delete all entries for (tenant, session_id).
     * Returns count of deleted rows.
     * Called by session-close endpoint and test teardown.
     */
    public int closeSession(String tenant, String sessionId) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            int deleted = dsl.deleteFrom(SCRATCH)
                .where(SCRATCH.SESSION_ID.eq(sessionId))
                .execute();
            log.info("event=t1_session_closed tenant={} session={} deleted={}", tenant, sessionId, deleted);
            return deleted;
        });
    }

    /**
     * TTL sweep: delete rows where {@code ts < cutoff}.
     * Returns count of deleted rows. Called by a service-internal timer as a
     * crash-safety backstop for sessions that never called session-close.
     *
     * <p>Runs WITHOUT tenant RLS stamping (superuser sweep across all tenants).
     * The caller (sweep endpoint or internal timer) must ensure it runs with
     * a superuser connection that has BYPASSRLS or via the Liquibase/superuser
     * connection, NOT via the nexus_svc role (which would silently skip rows for
     * unstamped tenants due to fail-closed RLS).
     */
    public int sweepExpired(DSLContext superuserDsl, OffsetDateTime cutoff) {
        int deleted = superuserDsl.deleteFrom(SCRATCH)
            .where(SCRATCH.TS.lt(cutoff))
            .execute();
        log.info("event=t1_ttl_sweep cutoff={} deleted={}", cutoff, deleted);
        return deleted;
    }

    /**
     * Per-tenant TTL sweep: delete rows for this tenant where {@code ts < cutoff}.
     * Uses {@link TenantScope} (tenant-scoped, RLS enforced). Called by the
     * /v1/t1/sweep endpoint for per-tenant cleanup; the cross-tenant superuser sweep
     * is deferred to bead .30.
     */
    public int sweepTenant(String tenant, OffsetDateTime cutoff) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            int deleted = dsl.deleteFrom(SCRATCH)
                .where(SCRATCH.TS.lt(cutoff))
                .execute();
            log.info("event=t1_tenant_sweep tenant={} cutoff={} deleted={}", tenant, cutoff, deleted);
            return deleted;
        });
    }

    /**
     * Resolve a UUID prefix to a full entry id, scoped to (tenant, session_id).
     * Returns all entry ids starting with {@code prefix} for this session.
     */
    public List<String> resolvePrefix(String tenant, String sessionId, String prefix) {
        return tenantScope.withTenant(tenant, T1_TENANT_GUC, dsl -> {
            return dsl.select(SCRATCH.ID)
                .from(SCRATCH)
                .where(SCRATCH.SESSION_ID.eq(sessionId)
                    .and(SCRATCH.ID.like(prefix + "%")))
                .orderBy(SCRATCH.TS.desc())
                .fetch(SCRATCH.ID);
        });
    }

    // ── Private helpers ────────────────────────────────────────────────────────

    /**
     * Convert a ScratchRecord to the Map shape expected by the Python client.
     * Mirrors the T1Database._to_row contract: keys match the Python field names.
     */
    Map<String, Object> toRow(ScratchRecord rec) {
        var m = new java.util.LinkedHashMap<String, Object>();
        m.put("id",            rec.getId());
        m.put("content",       rec.getContent());
        m.put("session_id",    rec.getSessionId());
        m.put("tags",          rec.getTags() != null ? rec.getTags() : "");
        m.put("flagged",       rec.getFlagged() != null ? rec.getFlagged() : false);
        m.put("flush_project", rec.getFlushProject() != null ? rec.getFlushProject() : "");
        m.put("flush_title",   rec.getFlushTitle() != null ? rec.getFlushTitle() : "");
        m.put("agent",         rec.getAgent() != null ? rec.getAgent() : "");
        m.put("access_count",  rec.getAccessCount());
        m.put("last_accessed", rec.getLastAccessed() != null
            ? rec.getLastAccessed().toString() : "");
        m.put("ts",            rec.getTs() != null ? rec.getTs().toString() : "");
        return m;
    }

    // ── Static import helpers for tsvector FTS ─────────────────────────────────

    /**
     * {@code plainto_tsquery(config, query)} SQL function.
     * Returns an untyped field (PG tsquery type has no Java mapping in jOOQ).
     */
    private static org.jooq.Field<Object> plaintoTsquery(
            org.jooq.Field<String> config, org.jooq.Field<String> query) {
        return field("plainto_tsquery({0}, {1})", Object.class, config, query);
    }
}
