# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Hal Hildebrand. All rights reserved.
"""Frozen T2 store contract — the parity oracle for RDR-158 P2 (nexus-jkzyq).

This is a FROZEN, machine-generated snapshot of the nine T2 SQLite store
classes' public method surface (method name -> ordered non-self parameter
names), captured while the SQLite stores were still the live oracle. It is
the durable replacement for the live-SQLite-oracle comparison the parity
tripwire (``test_http_t2_store_parity.py``) used to perform, so that tripwire
SURVIVES the SQLite store-class deletion in RDR-158 P4 (nexus-i711w).

Provenance: generated by introspecting the nine ``_STORE_PAIRS`` SQLite
oracles with the same public-only / ``_UNIVERSAL_IGNORE`` filter the tripwire
applies, using a classmethod-inclusive predicate
(``inspect.isfunction(x) or inspect.ismethod(x)``) so ``@classmethod`` members
such as ``CatalogTaxonomy.compute_cross_links`` are captured, not silently
dropped. RF-158-1: nine strict pairs, ``_EXCLUSIONS={}`` and
``_PARAM_DRIFT_OK={}`` — zero exemptions.

REGENERATE this artifact whenever an ``Http*`` store legitimately gains,
renames, or re-signatures a public method (re-run the generator against the
live classes). Until RDR-158 P4, ``test_contract_matches_live_sqlite_oracle``
cross-checks this snapshot against the live SQLite classes every run; after P4
the SQLite oracle is gone and this artifact is the sole authority, so a stale
snapshot would let Http*-store drift accumulate undetected — keep it current.
"""
from __future__ import annotations

# Methods present on every store base but not part of the storage contract.
_UNIVERSAL_IGNORE = {"close", "conn", "bootstrap_schema"}

# {store_label: {public_method_name: [ordered non-self parameter names]}}
T2_STORE_CONTRACT: dict[str, dict[str, list[str]]] = {
    'memory': {
        'delete': ['project', 'title', 'id'],
        'expire': [],
        'find_overlapping_memories': ['project', 'min_similarity', 'limit'],
        'flag_stale_memories': ['project', 'idle_days'],
        'get': ['project', 'title', 'id'],
        'get_all': ['project'],
        'get_projects_with_prefix': ['prefix'],
        'list_entries': ['project', 'agent'],
        'merge_memories': ['keep_id', 'delete_ids', 'merged_content'],
        'put': ['project', 'title', 'content', 'tags', 'ttl', 'agent', 'session'],
        'put_or_merge': ['project', 'title', 'content', 'tags', 'ttl', 'agent', 'session', 'min_similarity'],
        'resolve_title': ['project', 'title'],
        'search': ['query', 'project', 'access'],
        'search_by_tag': ['query', 'tag'],
        'search_glob': ['query', 'project_glob'],
    },
    'plans': {
        'delete_plan': ['plan_id'],
        'get_plan': ['plan_id'],
        'get_plan_by_dimensions': ['project', 'dimensions'],
        'increment_match_metrics': ['plan_id', 'confidence'],
        'increment_run_outcome': ['plan_id', 'success'],
        'increment_run_started': ['plan_id'],
        'list_active_plans': ['outcome', 'project'],
        'list_plans': ['limit', 'project', 'include_disabled'],
        'plan_exists': ['query', 'tag'],
        'save_plan': ['query', 'plan_json', 'outcome', 'tags', 'project', 'ttl', 'name', 'verb', 'scope', 'dimensions', 'default_bindings', 'parent_dims', 'scope_tags'],
        'search_plans': ['query', 'limit', 'project'],
        'set_plan_disabled': ['plan_id', 'reason'],
        'set_plan_enabled': ['plan_id'],
        'set_scope_tags': ['plan_id', 'scope_tags'],
    },
    'telemetry': {
        'expire_relevance_log': ['days'],
        'get_relevance_log': ['query', 'chunk_id', 'action', 'session_id', 'limit'],
        'log_relevance': ['query', 'chunk_id', 'action', 'session_id', 'collection'],
        'log_relevance_batch': ['rows'],
        'log_search_batch': ['rows'],
        'query_collection_stats': ['collection', 'days'],
        'record_hook_failure': ['doc_id', 'collection', 'hook_name', 'error',
                                'chain', 'batch_doc_ids', 'is_batch',
                                'occurred_at'],
        'record_nx_answer_run': ['question', 'plan_id', 'matched_confidence',
                                 'step_count', 'final_text', 'cost_usd',
                                 'duration_ms'],
        'record_tier_write': ['session_id', 'ts', 'tool', 'tier', 'agent',
                              'project', 'target_title'],
        'rename_collection': ['old', 'new'],
        'trim_search_telemetry': ['days'],
        'trim_hook_failures': ['days'],
    },
    'chash_index': {
        'count_for_collection': ['collection'],
        'delete_collection': ['collection'],
        'delete_stale': ['chash', 'collection'],
        'distinct_collections': [],
        'is_empty': [],
        'lookup': ['chash'],
        'registered_chashes_for_collection': ['collection'],
        'rename_collection': ['old', 'new'],
        'upsert': ['chash', 'collection'],
        'upsert_many': ['chashes', 'collection'],
    },
    'document_aspects': {
        'delete': ['collection', 'source_path'],
        'delete_orphans': ['catalog_db_path', 'dry_run'],
        'get': ['collection', 'source_path'],
        'get_by_doc_id': ['doc_id'],
        'get_salient_sentences': ['doc_id'],
        'list_by_collection': ['collection', 'limit', 'offset'],
        'list_by_extractor_version': ['extractor_name', 'max_version'],
        'rename_collection': ['old', 'new'],
        'set_salient_sentences': ['doc_id', 'sentences'],
        'set_salient_sentences_by_key': ['collection', 'source_path', 'sentences'],
        'upsert': ['record'],
    },
    'document_highlights': {
        'delete': ['doc_id'],
        'get': ['doc_id'],
        'get_by_source_uri': ['source_uri'],
        'list': ['limit', 'offset'],
        'upsert': ['record'],
    },
    'aspect_queue': {
        'claim_batch': ['limit'],
        'claim_next': [],
        'enqueue': ['collection', 'source_path', 'content_hash', 'content', 'doc_id'],
        'is_drained': [],
        'list_failed': ['collection'],
        'list_pending': ['limit'],
        'mark_done': ['collection', 'source_path', 'doc_id'],
        'mark_failed': ['collection', 'source_path', 'error'],
        'mark_retry': ['collection', 'source_path', 'interval_seconds'],
        'pending_count': [],
        'reclaim_stale': ['timeout_seconds'],
        'rename_collection': ['old', 'new'],
    },
    'taxonomy': {
        'assign_batch': ['collection_name', 'doc_ids', 'embeddings', 'chroma_client', 'cross_collection'],
        'assign_single': ['collection_name', 'embedding', 'chroma_client', 'cross_collection'],
        'assign_topic': ['doc_id', 'topic_id', 'assigned_by', 'similarity', 'source_collection', 'assigned_at'],
        'audit_collection': ['collection', 'threshold', 'top_n', 'stopwords'],
        'chunk_grounded_in': ['doc_id', 'source_collection', 'threshold'],
        'clear_icf_cache': [],
        'compute_assignments': ['collection_name', 'doc_ids', 'embeddings', 'chroma_client', 'cross_collection'],
        'compute_cross_links': ['collection_name', 'new_centroids', 'new_metas', 'centroid_coll'],
        'compute_discovered_topics': ['collection_name', 'doc_ids', 'embeddings', 'texts'],
        'compute_icf_map': ['use_cache'],
        'compute_rebuild_plan': ['collection_name', 'doc_ids', 'embeddings', 'texts', 'old_centroids', 'old_labels', 'old_review_statuses', 'old_centroid_topic_ids', 'manual_assignments'],
        'compute_split': ['topic_id', 'doc_ids', 'texts', 'fetched_ids', 'embeddings', 'collection_name', 'k'],
        'delete_topic': ['topic_id', 'chroma_client'],
        'detect_hubs': ['min_collections', 'max_icf', 'stopwords', 'warn_stale'],
        'discover_topics': ['collection_name', 'doc_ids', 'embeddings', 'texts', 'chroma_client'],
        'generate_cooccurrence_links': [],
        'get_all_topic_doc_ids': ['topic_id'],
        'get_all_topics': ['collection'],
        'get_assignments_for_docs': ['doc_ids'],
        'get_distinct_collections': [],
        'get_doc_ids_for_topic': ['label'],
        'get_labels_for_ids': ['topic_ids'],
        'get_projection_counts_by_collection': [],
        'get_topic_by_id': ['topic_id'],
        'get_topic_doc_ids': ['topic_id', 'limit'],
        'get_topic_docs': ['topic_id', 'limit'],
        'get_topic_link_pairs': ['topic_ids'],
        'get_topic_tree': ['collection', 'max_depth'],
        'get_topics': ['parent_id'],
        'get_topics_for_collection': ['collection', 'exclude_id'],
        'get_unreviewed_topics': ['collection', 'limit'],
        'mark_topic_reviewed': ['topic_id', 'status'],
        'merge_topics': ['source_id', 'target_id', 'chroma_client'],
        'needs_rebalance': ['collection', 'current_count'],
        'persist_assignments': ['assignments'],
        'persist_cross_links': ['pairs'],
        'persist_discovered_topics': ['collection_name', 'specs'],
        'persist_rebuild_topics': ['collection_name', 'plan'],
        'persist_split': ['split_result'],
        'project_against': ['source_collection', 'target_collections', 'chroma_client', 'threshold', 'top_k', 'icf_map', 'progress'],
        'purge_assignments_for_doc': ['project', 'title'],
        'purge_collection': ['collection'],
        'read_rebuild_old_state': ['collection_name', 'centroid_coll'],
        'rebuild_taxonomy': ['collection_name', 'doc_ids', 'embeddings', 'texts', 'chroma_client'],
        'record_discover_count': ['collection', 'doc_count'],
        'refresh_projection_links': [],
        'rename_collection': ['old', 'new'],
        'rename_topic': ['topic_id', 'new_label'],
        'resolve_label': ['label', 'collection'],
        'split_topic': ['topic_id', 'k', 'chroma_client'],
        'top_topics_for_collection': ['collection', 'top_n'],
        'update_topic_label': ['topic_id', 'new_label'],
        'upsert_topic_links': ['links'],
    },
    'scratch': {
        'clear': [],
        'delete': ['id'],
        'flag': ['id', 'project', 'title'],
        'flagged_entries': [],
        'get': ['id'],
        'list_entries': [],
        'promote': ['id', 'project', 'title', 't2'],
        'put': ['content', 'tags', 'persist', 'flush_project', 'flush_title', 'agent'],
        'resolve_prefix_candidates': ['id'],
        'search': ['query', 'n_results'],
        'unflag': ['id'],
    },
}

