provision:
  - mode: system
    script: |
      echo 'net.ipv4.ip_local_port_range = 32768 39999' > /etc/sysctl.d/90-nexus-docker-portrange.conf
      sysctl -q -w net.ipv4.ip_local_port_range="32768 39999"
      if systemctl is-active --quiet docker; then systemctl restart docker; fi
