# SPDX-License-Identifier: AGPL-3.0-or-later
"""Auto-approve sn plugin MCP tools (Serena + Context7) by explicit full name.

Declared in exec form (RDR-215 bead nexus-q02nx.23; launcher nexus-j4iy0) as
``uv run --no-project --no-config --quiet
${CLAUDE_PLUGIN_ROOT}/hooks/scripts/auto_approve_sn_mcp.py``, with
the hook payload on stdin and no argv, so the snapshot resolves to the
sibling serena-tools.txt. The bash wrapper it replaces passed that path
explicitly AND ended in an unconditional ``exit 0`` that hid a Python crash
completely; the wrapper is gone, so main() runs inside _hook_boundary.guard
instead -- a crash is logged to stderr rather than either swallowed or
fatal. That snapshot is generated by
scripts/sync_sn_serena_tools.py from the Serena revision pinned in
sn/.mcp.json (nexus-jbt5x: a hand-kept case list fell five tools behind and
every one of them prompted). No wildcards: a Serena tool the snapshot does
not name is not approved. Context7 has two tools and they are named here.

Event-aware output: PermissionRequest fires only when a prompt would be
shown; under defaultMode:auto the classifier decides first and never
consults it (cc-validation scenario 16, measured), so the same allowlist is
also registered on PreToolUse, where permissionDecision=allow lands before
the classifier. One allowlist, two events.

Worktree guard (nexus-ftpk3): before the allowlist is consulted, a Serena
WRITE tool called from a linked git worktree is DENIED. Serena resolves
paths against the root it found at startup, which for a worktree-dispatched
subagent is the shared primary checkout; three incidents wrote there while
the tool reported success. Detection and the write-tool set live in
worktree_guard.py, shared with subagent_start.py.

Relocated-session guard (nexus-ebx0s): the check above only catches a call
whose OWN cwd sits inside a linked worktree. It does not catch a session
that RELOCATED into a worktree by absolute path without its cwd ever
actually moving there (the Bash tool resets cwd to the primary after every
call) -- from cwd alone that call is indistinguishable from a session doing
legitimate primary work, since both have cwd == the primary. When the
worktree check does not fire, a second check compares this call's cwd
against the git working-tree root ``session_start.py`` recorded for this
session_id at ``startup`` (``worktree_guard.relocated_write_root``); a
mismatch denies too, regardless of whether either side is a linked
worktree. Fails OPEN (allows, and logs to stderr) whenever no session_id,
no recorded root, or an unresolvable cwd makes the comparison itself
impossible -- see that function's docstring.

Stdlib only: hooks run under system python with no conexus installed.
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import _hook_boundary  # noqa: E402 — bundled sibling, resolved by the path insert above

# Imported at module scope, ahead of the boundary, ON PURPOSE. subagent_start.py
# guards the identical import and degrades to "not a worktree"; here that would
# be wrong. This module's dependency IS the guard: with worktree_guard gone, the
# allowlist below would happily approve mcp__plugin_sn_serena__replace_in_files
# from a linked worktree, which is the incident (nexus-ftpk3, three of them)
# worktree_guard.py exists to prevent. Refusing to start means every sn tool
# prompts for manual approval, which is noisy and safe; degrading means the
# guard is silently off, which is quiet and not. Do not "make this consistent"
# with its sibling — the asymmetry is the decision.
from worktree_guard import (  # noqa: E402
    cwd_from_payload,
    deny_reason,
    deny_reason_relocated,
    is_linked_worktree,
    is_serena_write_tool,
    relocated_write_root,
)

CONTEXT7_TOOLS = frozenset({
    "mcp__plugin_sn_context7__resolve-library-id",
    "mcp__plugin_sn_context7__query-docs",
})
SERENA_PREFIX = "mcp__plugin_sn_serena__"


def allowed_tools(snapshot: pathlib.Path) -> frozenset[str]:
    names = set(CONTEXT7_TOOLS)
    try:
        lines = snapshot.read_text().splitlines()
    except OSError:
        return frozenset(names)  # snapshot missing: Serena tools prompt, nothing else changes
    for line in lines:
        line = line.strip()
        if line and not line.startswith("#"):
            names.add(SERENA_PREFIX + line)
    return frozenset(names)


def decide(payload: str, snapshot: pathlib.Path) -> str:
    """Return the JSON envelope for an allowed tool, else an empty string."""
    try:
        data = json.loads(payload)
    except (ValueError, TypeError):
        return ""
    if not isinstance(data, dict):
        return ""
    tool_name = data.get("tool_name", "")
    event = data.get("hook_event_name", "PermissionRequest")
    if is_serena_write_tool(tool_name):
        cwd = cwd_from_payload(payload)
        reason = None
        if is_linked_worktree(cwd):
            reason = deny_reason(tool_name, cwd)
        else:
            session_id = data.get("session_id", "")
            session_id = session_id if isinstance(session_id, str) else ""
            recorded = relocated_write_root(cwd, session_id)
            if recorded is not None:
                reason = deny_reason_relocated(tool_name, cwd, recorded)
        if reason is not None:
            if event == "PreToolUse":
                out = {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            else:
                out = {
                    "hookEventName": "PermissionRequest",
                    "decision": {"behavior": "deny", "message": reason},
                }
            return json.dumps({"hookSpecificOutput": out})
    if tool_name not in allowed_tools(snapshot):
        return ""
    if event == "PreToolUse":
        out = {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
            "permissionDecisionReason": "plugin allowlist (auto-approve)",
        }
    else:
        out = {"hookEventName": "PermissionRequest", "decision": {"behavior": "allow"}}
    return json.dumps({"hookSpecificOutput": out})


def main() -> int:
    snapshot = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).with_name("serena-tools.txt")
    result = decide(sys.stdin.read(), snapshot)
    if result:
        print(result)  # noqa: T201 — stdout IS this hook's decision channel
    return 0


if __name__ == "__main__":
    sys.exit(_hook_boundary.guard(main, "sn-auto-approve"))
