# SPDX-License-Identifier: AGPL-3.0-or-later
"""Auto-approve sn plugin MCP tools (Serena + Context7) by explicit full name.

Invoked by auto-approve-sn-mcp.sh with the hook payload on stdin and the
path of serena-tools.txt as argv[1]. That snapshot is generated by
scripts/sync_sn_serena_tools.py from the Serena revision pinned in
sn/.mcp.json (nexus-jbt5x: a hand-kept case list fell five tools behind and
every one of them prompted). No wildcards: a Serena tool the snapshot does
not name is not approved. Context7 has two tools and they are named here.

Event-aware output: PermissionRequest fires only when a prompt would be
shown; under defaultMode:auto the classifier decides first and never
consults it (cc-validation scenario 16, measured), so the same allowlist is
also registered on PreToolUse, where permissionDecision=allow lands before
the classifier. One allowlist, two events.

Worktree guard (nexus-ftpk3): before the allowlist is consulted, a Serena
WRITE tool called from a linked git worktree is DENIED. Serena resolves
paths against the root it found at startup, which for a worktree-dispatched
subagent is the shared primary checkout; three incidents wrote there while
the tool reported success. Detection and the write-tool set live in
worktree_guard.py, shared with mcp-inject.sh.

Stdlib only: hooks run under system python with no conexus installed.
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from worktree_guard import cwd_from_payload, deny_reason, is_linked_worktree, is_serena_write_tool  # noqa: E402

CONTEXT7_TOOLS = frozenset({
    "mcp__plugin_sn_context7__resolve-library-id",
    "mcp__plugin_sn_context7__query-docs",
})
SERENA_PREFIX = "mcp__plugin_sn_serena__"


def allowed_tools(snapshot: pathlib.Path) -> frozenset[str]:
    names = set(CONTEXT7_TOOLS)
    try:
        lines = snapshot.read_text().splitlines()
    except OSError:
        return frozenset(names)  # snapshot missing: Serena tools prompt, nothing else changes
    for line in lines:
        line = line.strip()
        if line and not line.startswith("#"):
            names.add(SERENA_PREFIX + line)
    return frozenset(names)


def decide(payload: str, snapshot: pathlib.Path) -> str:
    """Return the JSON envelope for an allowed tool, else an empty string."""
    try:
        data = json.loads(payload)
    except (ValueError, TypeError):
        return ""
    if not isinstance(data, dict):
        return ""
    tool_name = data.get("tool_name", "")
    event = data.get("hook_event_name", "PermissionRequest")
    if is_serena_write_tool(tool_name):
        cwd = cwd_from_payload(payload)
        if is_linked_worktree(cwd):
            reason = deny_reason(tool_name, cwd)
            if event == "PreToolUse":
                out = {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            else:
                out = {
                    "hookEventName": "PermissionRequest",
                    "decision": {"behavior": "deny", "message": reason},
                }
            return json.dumps({"hookSpecificOutput": out})
    if tool_name not in allowed_tools(snapshot):
        return ""
    if event == "PreToolUse":
        out = {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
            "permissionDecisionReason": "plugin allowlist (auto-approve)",
        }
    else:
        out = {"hookEventName": "PermissionRequest", "decision": {"behavior": "allow"}}
    return json.dumps({"hookSpecificOutput": out})


def main() -> int:
    snapshot = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).with_name("serena-tools.txt")
    result = decide(sys.stdin.read(), snapshot)
    if result:
        print(result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
