#!/bin/bash
# Auto-approve sn plugin MCP tools (Serena + Context7) by explicit full name.
# The decision lives in auto_approve_sn_mcp.py beside this script; the Serena
# names come from serena-tools.txt, generated by scripts/sync_sn_serena_tools.py
# from the revision pinned in sn/.mcp.json. See the .py docstring.
# No set -e: a failure here must not kill the hook (the user just sees the prompt).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python3 "$SCRIPT_DIR/auto_approve_sn_mcp.py" "$SCRIPT_DIR/serena-tools.txt" 2>/dev/null
exit 0
