# SPDX-License-Identifier: AGPL-3.0-or-later
"""nx agents — generate user-scope Claude Code agents from installed plugin parts.

``nx agents install worktree-developer`` (nexus-uympf) composes
``~/.claude/agents/worktree-developer.md`` from two files the installed
plugins already ship:

* ``sn/examples/worktree-developer.md`` — the frontmatter that declares the
  agent's PRIVATE Serena MCP server (``serena-wt``, pinned to the same
  revision as ``sn/.mcp.json``) and the activation preamble that roots it at
  the worktree; and
* ``conexus/agents/developer.md`` — the developer method (pre-flight tier
  reads, test-first, circuit breaker, completion protocol).

Plugin-shipped agents cannot declare ``mcpServers`` (cc-validation scenario
14b), so the composed agent has to live in the user's own ``~/.claude/agents``.
A hand-copied file there drifts from the plugin the moment either input
changes; generating it from the INSTALLED plugin directories keeps it at the
pinned release, and ``--check`` reports drift without writing.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import click
import structlog
import yaml

_log = structlog.get_logger()

INSTALLED_PLUGINS = Path.home() / ".claude" / "plugins" / "installed_plugins.json"
AGENTS_DIR = Path.home() / ".claude" / "agents"

#: Frontmatter keys copied from the developer agent when the template lacks them.
_INHERITED_KEYS = ("model", "color", "effort")
_GENERATED_MARK = "<!-- generated by `nx agents install worktree-developer`"
_SHARED_LINK = re.compile(r"\]\(\./_shared/")


def _split_frontmatter(text: str, *, what: str) -> tuple[str, str]:
    """Return ``(frontmatter, body)`` for a ``---``-fenced markdown file."""
    if not text.startswith("---\n"):
        raise click.ClickException(f"{what}: no frontmatter fence")
    parts = text.split("\n---\n", 1)
    if len(parts) != 2:
        raise click.ClickException(f"{what}: unterminated frontmatter")
    return parts[0][4:], parts[1]


def _frontmatter_keys(fm: str, *, what: str) -> dict:
    """Parsed frontmatter mapping; a non-mapping or unparsable block is a hard error."""
    try:
        data = yaml.safe_load(fm)
    except yaml.YAMLError as exc:
        raise click.ClickException(f"{what}: frontmatter is not valid YAML ({exc})") from exc
    if not isinstance(data, dict):
        raise click.ClickException(f"{what}: frontmatter is not a mapping")
    return data


def installed_plugin_dir(name: str, *, manifest: Path = INSTALLED_PLUGINS) -> Path:
    """Install path of ``<name>@nexus-plugins`` from Claude Code's manifest."""
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise click.ClickException(
            f"{manifest} unreadable ({exc}); install the plugins first "
            f"(/plugin install {name}@nexus-plugins) or pass --{name}-dir"
        ) from exc
    if not isinstance(data, dict):
        raise click.ClickException(f"{manifest}: not a JSON object; pass --{name}-dir")
    entries = data.get("plugins", {}).get(f"{name}@nexus-plugins") or []
    for entry in entries:
        path = Path(str(entry.get("installPath", "")))
        if path.is_dir():
            return path
    raise click.ClickException(
        f"{name}@nexus-plugins is not installed (no installPath in {manifest}); "
        f"run /plugin install {name}@nexus-plugins or pass --{name}-dir"
    )


def _plugin_version(plugin_dir: Path) -> str:
    try:
        return str(json.loads((plugin_dir / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8")).get("version", "?"))
    except (OSError, json.JSONDecodeError):
        return "?"


def compose_worktree_developer(*, sn_dir: Path, conexus_dir: Path) -> str:
    """Compose the agent text from the sn template and the conexus developer.

    Frontmatter: the template's, plus ``model``/``color``/``effort`` inherited
    from the developer when the template does not set them (``name`` and
    ``mcpServers`` always come from the template). Body: a generated-by
    marker, the template's activation preamble, then the developer body with
    its ``./_shared/`` links rewritten to the installed conexus directory so
    they resolve from ``~/.claude/agents``.
    """
    template_path = sn_dir / "examples" / "worktree-developer.md"
    developer_path = conexus_dir / "agents" / "developer.md"
    try:
        template = template_path.read_text(encoding="utf-8")
        developer = developer_path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise click.ClickException(f"missing input: {exc.filename}") from exc

    t_fm, t_body = _split_frontmatter(template, what=str(template_path))
    d_fm, d_body = _split_frontmatter(developer, what=str(developer_path))

    # Key sets come from a real YAML parse; the line splice below only
    # reconstructs output, so the template's mcpServers block keeps its exact
    # formatting (a safe_dump round-trip would reflow it).
    present = _frontmatter_keys(t_fm, what=str(template_path))
    developer_meta = _frontmatter_keys(d_fm, what=str(developer_path))
    fm_lines = t_fm.rstrip("\n").split("\n")
    inherited = [
        f"{key}: {developer_meta[key]}"
        for key in _INHERITED_KEYS
        if key in developer_meta and key not in present
    ]
    # ``mcpServers`` is a multi-line block; keep it last so scalar keys precede it.
    try:
        idx = next(i for i, line in enumerate(fm_lines) if line.startswith("mcpServers:"))
    except StopIteration:
        raise click.ClickException(f"{template_path}: frontmatter declares no mcpServers")
    fm_lines[idx:idx] = inherited

    shared_dir = (conexus_dir.resolve() / "agents" / "_shared").as_posix()
    d_body = _SHARED_LINK.sub(f"]({shared_dir}/", d_body)

    digest = hashlib.sha256((template + developer).encode("utf-8")).hexdigest()[:16]
    marker = (
        f"{_GENERATED_MARK} from sn {_plugin_version(sn_dir)} + conexus "
        f"{_plugin_version(conexus_dir)}; inputs sha256 {digest}. Do not edit; re-run to refresh. -->"
    )
    return (
        "---\n" + "\n".join(fm_lines) + "\n---\n"
        + marker + "\n"
        + t_body.strip("\n") + "\n\n---\n\n"
        + d_body.strip("\n") + "\n"
    )


def worktree_developer_drift(*, dest: Path = AGENTS_DIR / "worktree-developer.md",
                             manifest: Path = INSTALLED_PLUGINS) -> str | None:
    """Drift probe for ``nx doctor``: ``None`` when the agent is absent (opt-in,
    nothing to say) or current; otherwise one line naming what is wrong.
    Never raises: the plugins being uninstalled is reported, not thrown."""
    if not dest.is_file():
        return None
    try:
        text = compose_worktree_developer(
            sn_dir=installed_plugin_dir("sn", manifest=manifest),
            conexus_dir=installed_plugin_dir("conexus", manifest=manifest),
        )
    except click.ClickException as exc:
        return f"cannot recompose {dest}: {exc.message}"
    if dest.read_text(encoding="utf-8") != text:
        return f"{dest} differs from the installed plugins"
    return None


@click.group("agents")
def agents_group() -> None:
    """Generate user-scope Claude Code agents from installed plugin parts."""


@agents_group.command("install")
@click.argument("name", type=click.Choice(["worktree-developer"]))
@click.option("--check", is_flag=True, help="Exit 1 if the installed agent differs from what would be generated; write nothing.")
@click.option("--dry-run", is_flag=True, help="Print the composed agent instead of writing it.")
@click.option("--sn-dir", type=click.Path(path_type=Path), default=None, help="sn plugin directory (default: the installed sn@nexus-plugins).")
@click.option("--conexus-dir", type=click.Path(path_type=Path), default=None, help="conexus plugin directory (default: the installed conexus@nexus-plugins).")
@click.option("--dest", type=click.Path(path_type=Path), default=None, help=f"Output file (default: {AGENTS_DIR}/<name>.md).")
def install_cmd(name: str, check: bool, dry_run: bool, sn_dir: Path | None, conexus_dir: Path | None, dest: Path | None) -> None:
    """Compose NAME from the installed plugins and write it to ~/.claude/agents.

    The worktree-developer is the conexus developer agent with a private
    Serena MCP server rooted at its own worktree (sn examples/). Dispatch it
    with subagent_type "worktree-developer" and isolation "worktree"; allow
    mcp__serena-wt__* in ~/.claude/settings.json permissions.
    """
    if check and dry_run:
        raise click.UsageError("--check and --dry-run are mutually exclusive")
    sn_dir = sn_dir or installed_plugin_dir("sn")
    conexus_dir = conexus_dir or installed_plugin_dir("conexus")
    dest = dest or AGENTS_DIR / f"{name}.md"
    text = compose_worktree_developer(sn_dir=sn_dir, conexus_dir=conexus_dir)

    if dry_run:
        click.echo(text, nl=False)
        return
    current = dest.read_text(encoding="utf-8") if dest.exists() else None
    if check:
        if current == text:
            click.echo(f"{dest}: up to date")
            return
        click.echo(f"{dest}: {'missing' if current is None else 'differs from the installed plugins'}; run nx agents install {name}")
        raise SystemExit(1)
    if current == text:
        click.echo(f"{dest}: already up to date")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    _log.info("agent_installed", agent=name, dest=str(dest), sn=str(sn_dir), conexus=str(conexus_dir))
    click.echo(f"{'updated' if current is not None else 'wrote'} {dest} (sn {_plugin_version(sn_dir)}, conexus {_plugin_version(conexus_dir)})")
