# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Hal Hildebrand. All rights reserved.
"""Content-addressed line anchors for line-keyed lint exemption ledgers
(nexus-vkpr3).

THE DEFECT THIS CLOSES. Several repo-wide lint ratchets in this directory
carry an EXEMPTION SET keyed by ``"<path>:<lineno>"`` (or a ``(path,
lineno)`` tuple): a documented, reviewed reason for NOT flagging one
specific violation site. Keying by line number is silently wrong the
moment anything is inserted ABOVE the exempted line -- the number no
longer names the site it was written for, it names whatever code now
happens to sit at that number. Two confirmed incidents on the same file,
same day (nexus-vkpr3, 2026-09-12/13): inserting 11-13 and then 17 more
lines above a block of twelve pipefail-lint exemptions re-pointed every
one of them onto a different line. Both times the sweep's own "still a
live violation" check caught the shift LOUDLY -- but the recovery it
demanded (retarget every entry to its new line) only avoided silently
mis-exempting a new, unreviewed site because the entries were matched
old-to-new BY CONTENT, not by an arithmetic line offset. An offset that
happens to be right for MOST entries is exactly the failure mode this
closes: the ones it gets wrong are silent, and the wrong direction is
the dangerous one -- a real, never-reviewed violation landing under an
exemption whose rationale was written for different code entirely, with
the gate staying green throughout.

THE FIX. Key an exemption on the VIOLATING LINE'S OWN CONTENT -- one or
more consecutive stripped source lines, in file order, ending at the
target line -- instead of its line number. A pure insertion above the
site changes no line's TEXT, so the anchor keeps matching the same
physical code after the shift; `resolve_anchor` below re-derives the
CURRENT line number from the content every time a ledger is checked, so
no stored number is ever load-bearing between runs. An anchor that no
longer occurs anywhere in the file (the line was fixed, deleted, or
rewritten) fails loud as STALE; one that occurs more than once fails
loud as AMBIGUOUS, rather than silently guessing which occurrence the
entry meant.

WHY A MULTI-LINE BLOCK, NOT JUST A LONGER SUBSTRING. A single stripped
line is not always unique within a file on its own (e.g. ``head -1)"``
alone recurs roughly five times in one real migration-rehearsal script)
-- widening to a longer SUBSTRING of that same single line is still
line-scoped and just as capable of coincidentally matching a different,
unrelated occurrence of the identical line elsewhere in the file.
Widening to a CONTIGUOUS BLOCK of consecutive lines (the target line
plus however many immediately preceding lines it takes to become
unique) stays anchored to the surrounding code's own content, which
shifts by the same delta as the target line under any insertion above
it, so the block keeps matching as one unit after the shift.

MANDATORY TWO-LINE MINIMUM (fix-round finding, same day: a substantive-
critic pass on the first version of this module found a residual silent-
mistarget hazard the design above did not close). The first version only
widened an anchor past one line when the CURRENT snapshot already showed
a same-file duplicate -- an entry that was unique at authoring time
stayed a single line. That is not enough: if the exempted line is later
edited away (fixed, deleted) and an UNRELATED new violation elsewhere in
the same file happens to have byte-identical stripped text, a one-line
anchor finds exactly that one match and silently "resolves" to it --
exactly the mis-exemption direction this whole mechanism exists to
close, just moved from "line shifted" to "line coincidentally
duplicated". The convention every caller in this repo follows as of
this fix: an anchor's content ALWAYS includes the target line's nearest
preceding NON-BLANK line as a second, leading element (falling back to a
single line only when the target has no preceding non-blank line at all
-- the very top of a file). `resolve_anchor` enforces the matching
mechanics for this (see the blank-line handling below); it does not
reject a caller-supplied one-line anchor outright, because a handful of
legitimate top-of-file sites have no context line to pair with, and
because widening further (3+ lines) is still sometimes needed to
disambiguate a genuine duplicate PAIR -- but every ledger in this repo
is authored, and regenerated by a verifying script, to the two-line
convention by default.

RESIDUAL RISK, STATED PLAINLY, NOT CLAIMED CLOSED: two-line anchoring
narrows the coincidence a future edit needs to cause a silent mistarget
from "one identical line" to "two CONSECUTIVE identical lines" (the
target line preceded by the same non-blank line, skipping any blanks in
between) -- it does not make the hazard structurally impossible. A
three-or-more-line anchor narrows it further at the cost of more brittle
matching (more surrounding code that must stay byte-identical for the
anchor to keep resolving at all, i.e. more STALE churn on ordinary
nearby edits). This module does not attempt to eliminate the hazard
outright; it makes the practical coincidence needed to trigger it
strictly less likely than a single-line anchor, which is the same
trade-off every content-based identity scheme in this repo makes (chunk
hashing, symbol name paths) -- more context lowers collision odds, it
never proves zero.

BLANK-LINE HANDLING. The "nearest preceding non-blank line" in the
mandatory convention above is not always the physically adjacent line --
a blank line (or several) may sit between the target and its nearest
real context. `resolve_anchor` matches *content_lines* against the
file's NON-BLANK lines only (blank/whitespace-only lines are filtered
out of the search sequence before windowing), so a caller's
(preceding_line, target_line) pair matches correctly even when a blank
line physically separates them in the file -- comment lines DO count as
non-blank context, deliberately, since they disambiguate just as well as
code (and several real entries in this repo's ledgers use exactly that).
"""
from __future__ import annotations

from pathlib import Path
from typing import TypeVar

_NO_FILE = "no such file: {path}"
_EMPTY = "empty content anchor for {path}"
_STALE = (
    "content no longer found in {path} (STALE exemption -- the line was "
    "fixed, deleted, or rewritten; drop the entry): {content!r}"
)
_AMBIGUOUS = (
    "content occurs {n} times in {path} at lines {lines} (AMBIGUOUS "
    "exemption -- widen the anchor with a leading line of unique "
    "context instead of guessing which occurrence was meant): {content!r}"
)

_T = TypeVar("_T")


def resolve_anchor(
    repo_root: Path, rel_path: str, content_lines: tuple[str, ...],
) -> tuple[int | None, str]:
    """Resolve *content_lines* -- one or more consecutive STRIPPED
    NON-BLANK source lines, in file order, ending at the exempted line
    -- to that line's CURRENT 1-based line number inside *rel_path*
    (relative to *repo_root*).

    Blank/whitespace-only lines are transparently skipped on both sides
    of the match (see BLANK-LINE HANDLING above): *content_lines* is
    matched as a contiguous window over the file's non-blank lines only,
    so a caller's (nearest-preceding-non-blank-line, target-line) pair
    resolves correctly even when a blank line physically separates them.

    Returns ``(lineno, "")`` on exactly one match. Returns ``(None,
    reason)`` when the file does not exist, the block occurs nowhere in
    the file (STALE), or it occurs more than once (AMBIGUOUS) -- a
    caller must treat either failure as loud, never as "assume the
    first match" or "assume the site is still clean".
    """
    if not content_lines:
        return None, _EMPTY.format(path=rel_path)
    full = repo_root / rel_path
    if not full.is_file():
        return None, _NO_FILE.format(path=rel_path)
    lines = full.read_text(encoding="utf-8", errors="replace").splitlines()
    # (original 1-based lineno, stripped text) for NON-BLANK lines only --
    # this is what content_lines windows against, so a blank line between
    # a caller's context line and its target is transparently skipped.
    non_blank = [(i + 1, s) for i, ln in enumerate(lines) if (s := ln.strip())]
    texts = [t for _, t in non_blank]
    n = len(content_lines)
    matches = [
        non_blank[i + n - 1][0]  # original lineno of the LAST line in the window
        for i in range(len(texts) - n + 1)
        if tuple(texts[i:i + n]) == content_lines
    ]
    if not matches:
        return None, _STALE.format(path=rel_path, content=content_lines)
    if len(matches) > 1:
        return None, _AMBIGUOUS.format(
            path=rel_path, n=len(matches), lines=matches, content=content_lines,
        )
    return matches[0], ""


def resolve_ledger(
    repo_root: Path, items: list[tuple[str, tuple[str, ...], _T]],
) -> tuple[list[tuple[str, int, _T]], list[str]]:
    """Resolve every ``(path, content_anchor, payload)`` triple in
    *items* via `resolve_anchor`, once each. Shared by every converted
    lint-exemption ledger in this repo (nexus-vkpr3 fix round) so the
    resolve-then-report shape isn't hand-duplicated per file.

    Returns ``(resolved, problems)``: *resolved* is a flat list of
    ``(path, resolved_lineno, payload)`` triples (payload passed through
    unchanged -- a ledger's own value, an extra key component, or
    ``None`` for a membership-only set); *problems* is the list of
    STALE/AMBIGUOUS diagnostics for anchors that did not resolve.
    *payload* is opaque here so callers with different ledger shapes
    (a bare membership set, a ``reason`` string, a composite key with
    extra fields) can each rebuild their own preferred dict/set shape
    from the flat result without this function needing to know it.
    """
    resolved: list[tuple[str, int, _T]] = []
    problems: list[str] = []
    for path, content, payload in items:
        lineno, err = resolve_anchor(repo_root, path, content)
        if err:
            problems.append(f"{path} {content!r} -> {err}")
            continue
        resolved.append((path, lineno, payload))
    return resolved, problems
