# SPDX-License-Identifier: AGPL-3.0-or-later
"""RDR-225 P1.1 (nexus-3wh8d.6): the lint that guards the RDR's failure mode
"a write site missed in the rewrite".

``docs/rdr/rdr-225-inventory.json`` pins every object that names ``nexus.chunks``,
``taxonomy_centroids``, ``catalog_document_chunks``, ``topic_assignments`` or
``chunk_orphaned_at``, generated by ``scripts/rdr225_inventory.py``. These tests fail when
the tree names one of those tables somewhere the pinned file does not list, or lists it
differently. The remedy for a failure is never to edit the pinned file by hand: run
``python scripts/rdr225_inventory.py --write``, read the diff, and (for a write site)
make sure the RDR-225 migration rewrites it. P1.3's migration changeset will itself
change this inventory, and that is expected.

The failing direction is proved on a tmp COPY of the real changelog and Java trees with
an unlisted object added, never by editing the repo.
"""
from __future__ import annotations

import ast
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

import rdr225_inventory as inv

pytestmark = pytest.mark.lint

CHANGELOG_FILES = 175  # measured 2026-10-06; a floor, the real tree only grows


# The roots and the pinned file are read by fixtures, never at import: a missing or unreadable
# pinned file is a failed test with a message, not a collection error that hides the module.


@pytest.fixture(scope="module")
def real() -> inv.Roots:
    return inv.default_roots()


@pytest.fixture(scope="module")
def pinned() -> dict:
    if not inv.PINNED_PATH.exists():
        pytest.fail(f"the pinned RDR-225 inventory is missing: {inv.PINNED_PATH}. Generate it with "
                    "python scripts/rdr225_inventory.py --write", pytrace=False)
    return inv.load_pinned()


# ---------------------------------------------------------------------------
# The pinned inventory is current
# ---------------------------------------------------------------------------


def test_pinned_inventory_is_current_and_covers_every_table_naming_location(real: inv.Roots, pinned: dict) -> None:
    problems = inv.problems(real, pinned)
    assert problems == [], (
        "the pinned RDR-225 inventory is stale. Review each line below; if it is a new or "
        "changed write site make sure the RDR-225 migration rewrites it, then regenerate: "
        "python scripts/rdr225_inventory.py --write\n" + "\n".join(problems[:40])
    )


def test_inventory_is_non_vacuous(real: inv.Roots, pinned: dict) -> None:
    """A scanner that silently matched nothing would also be 'current' (the
    nexus-moht0 vacuous-gate class), so pin floors measured on 2026-10-06."""
    rows = pinned["rows"]
    assert len(rows) >= 600
    assert len(list(real.changelog_dir.glob("*.xml"))) >= CHANGELOG_FILES
    kinds = {r["kind"] for r in rows}
    assert {"fk", "constraint", "index", "policy", "rls", "trigger", "view", "function", "do-block", "dml",
            "grant-schema-wide", "java-method", "python-anchor", "table"} <= kinds
    for table in inv.TABLES:
        sql = [r for r in rows if r["source"] == "changelog" and table in r["tables"]]
        java = [r for r in rows if r["source"] == "java" and table in r["tables"]]
        assert len(sql) >= 5, f"{table}: only {len(sql)} changelog rows"
        assert len(java) >= 1, f"{table}: no Java row"
    writers = [r for r in rows if r["source"] == "java"
               and any(s["verb"] == "INSERT" for s in r["sites"])]
    assert len(writers) >= 8
    # rows carry their forms
    for r in rows:
        assert r["rdr_row"] in {t["id"] for t in pinned["td_rows"]}
        assert r["new_form"] and r["fallback_form"]


# ---------------------------------------------------------------------------
# Every row of the RDR's Technical Design table appears
# ---------------------------------------------------------------------------


def _rows_named(pinned: dict, name: str, **where):
    return [r for r in pinned["rows"] if r["name"] == name and all(r.get(k) == v for k, v in where.items())]


def _td_ids(row) -> set[str]:
    return {row["rdr_row"], *row.get("rdr_also", [])}


# (Technical Design row id, what the inventory must hold for it). Each entry is a named
# object the RDR table lists, resolved to a row by name and kind.
REQUIRED_OBJECTS = [
    ("T01", "fk_catalog_chunks_chunk", {"kind": "fk", "live": True}),
    ("T02", "topic_assignments_chunk_fk", {"kind": "fk", "live": True}),
    ("T03", "chunk_orphaned_at_chunk_fk", {"kind": "fk", "live": True}),
    ("T04", "chunks_collection_fk", {"kind": "fk", "live": True}),
    ("T06", "stamp_chunks_on_manifest_delete", {"kind": "function", "live": True}),
    ("T06", "stamp_chunks_on_manifest_update", {"kind": "function", "live": True}),
    ("T07", "live_chunks", {"kind": "view", "live": True}),
    ("T07", "collection_vector_stats", {"kind": "view", "live": True}),
    ("T08", "chunks_gate_probe_owner_read", {"kind": "policy", "live": True}),
    ("T08", "tenant_isolation", {"kind": "policy", "live": True, "host": "chunks"}),
    ("T09", "chunks_content_retention_consistent", {"kind": "constraint", "live": True}),
    ("T09", "chunks_chash_octet_check", {"kind": "constraint", "live": True}),
    ("T09", "idx_chunks_tenant_chash", {"kind": "index", "live": True}),
    ("T09", "idx_chunks_embedding_1024", {"kind": "index", "live": True}),
    ("T09", "idx_chunks_tsv", {"kind": "index", "live": True}),
    ("T09", "idx_chunks_trgm", {"kind": "index", "live": True}),
    ("T12", "taxonomy_centroids", {"kind": "table", "live": True}),
    ("P-PK", "chunks_pk", {"kind": "constraint", "live": True}),
    ("P-DIM", "exactly_one_embedding", {"kind": "constraint", "live": True}),
]


@pytest.mark.parametrize("td,name,where", REQUIRED_OBJECTS, ids=[f"{t}:{n}" for t, n, _ in REQUIRED_OBJECTS])
def test_named_object_from_the_technical_design_table_is_inventoried(pinned: dict, td: str, name: str, where: dict) -> None:
    rows = _rows_named(pinned, name, **where)
    assert rows, f"{name} ({where}) is not in the inventory"
    assert any(td in _td_ids(r) for r in rows), (name, [r["rdr_row"] for r in rows])


def test_diag_chash_conformance_view_is_inventoried_through_its_runalways_do_block(pinned: dict) -> None:
    rows = [r for r in pinned["rows"] if "view:diag_chash_conformance" in r.get("defines", [])]
    assert rows and all(r["run_always"] for r in rows)
    assert all("T07" in _td_ids(r) for r in rows)


def test_grants_are_inventoried_in_both_grant_changelogs(pinned: dict) -> None:
    files = {r["file"].rsplit("/", 1)[-1] for r in pinned["rows"] if "T10" in _td_ids(r)}
    assert {"grants-nexus-svc.xml", "grants-nexus-diag.xml"} <= files
    assert all(r["run_always"] for r in pinned["rows"] if "T10" in _td_ids(r) and r["source"] == "changelog")


def test_isolation_checks_are_inventoried(pinned: dict) -> None:
    java = [r for r in pinned["rows"] if r["name"].startswith("ChunksIsolationCheck/")]
    assert java and all("T11" in _td_ids(r) for r in java)
    py = [r for r in pinned["rows"] if r["kind"] == "python-anchor"]
    assert {r["name"] for r in py} >= {"_RLS_TENANT_TABLES", "_RLS_TENANT_TABLES:nexus.chunks"}


def test_router_probe_is_inventoried(pinned: dict) -> None:
    rows = _rows_named(pinned, "PgVectorRepository/probeSelectedRows")
    assert len(rows) == 1
    assert rows[0]["rdr_row"] == "P-ROUTER"
    assert any(s["verb"] == "READ" and s["table"] == "chunks" for s in rows[0]["sites"])


def test_centroid_upsert_is_inventoried_with_its_conflict_target(pinned: dict) -> None:
    (row,) = _rows_named(pinned, "TaxonomyCentroidRepository/upsertCentroids")
    (site,) = [s for s in row["sites"] if s["verb"] == "INSERT"]
    assert site["table"] == "taxonomy_centroids"
    assert site["conflict"] == "(tenant_id, collection, topic_id) DO UPDATE"
    assert "T12" in _td_ids(row)


def test_raw_chunk_upsert_and_manifest_upsert_are_inventoried(pinned: dict) -> None:
    (chunk,) = _rows_named(pinned, "PgVectorRepository/upsertChunksInternal")
    site = next(s for s in chunk["sites"] if s["verb"] == "INSERT" and s["table"] == "chunks")
    assert site["conflict"] == "(tenant_id, collection, chash) DO UPDATE"
    assert "embedding_model" not in site["columns"]  # today; P1.3 adds it
    (manifest,) = _rows_named(pinned, "CatalogRepository/insertManifestChunkRows")
    msite = next(s for s in manifest["sites"] if s["verb"] == "INSERT")
    assert msite["table"] == "catalog_document_chunks"
    assert "(tenant_id, doc_id, position)" in msite["conflict"]
    assert "T05" in _td_ids(manifest)


def test_set_constraints_sites_named_by_the_rdr_are_all_present(pinned: dict) -> None:
    sites = {
        (r["file"].rsplit("/", 1)[-1], s["line"])
        for r in pinned["rows"] for s in r["sites"] if s["verb"] == "SET CONSTRAINTS"
    }
    # the RDR names catalog-029:306, catalog-033:99 and 199, vectors-017:1064 and 1177 (plpgsql)
    # and CatalogRepository.java:8297 (Java; 8298 at 1fe753cb4, the line drifts with the file)
    for fname, line in [
        ("catalog-029-manifest-chunk-fk.xml", 306), ("catalog-033-gc-audit-producers.xml", 99),
        ("catalog-033-gc-audit-producers.xml", 199),
        ("vectors-017-collection-scoped-tombstone-filter.xml", 1064),
        ("vectors-017-collection-scoped-tombstone-filter.xml", 1177),
    ]:
        assert (fname, line) in sites, (fname, line)
    assert any(f == "CatalogRepository.java" for f, _ in sites)


@pytest.mark.parametrize("name,live_changeset", [
    ("gc_quarantine_orphans", "vectors-022-1"),
    ("gc_quarantine_orphans_bounded", "vectors-022-2"),
    ("reaper_quarantine_chunks", "vectors-024-1"),
    ("gc_restore_rereferenced", "catalog-043-2"),
    ("gc_restore_rereferenced_bounded", "catalog-043-1"),
    ("quarantine_restore_chunks", "vectors-025-2"),
    ("purge_trash", "vectors-017-3"),
])
def test_function_rows_record_which_changeset_holds_the_live_body(pinned: dict, name: str, live_changeset: str) -> None:
    rows = [r for r in pinned["rows"] if r["kind"] == "function" and r["name"] == name]
    live = [r for r in rows if r["live"]]
    assert len(live) == 1, (name, [(r["changeset"], r["live"]) for r in rows])
    assert live[0]["changeset"] == live_changeset
    assert live[0]["live_in"].endswith("#" + live_changeset)
    for r in rows:
        assert r["live_in"].endswith("#" + live_changeset)  # superseded rows point at the live one
        assert r["rdr_row"] == "X2" or r is live[0]


BEAD_COMMENT_CHANGELOGS = [
    "catalog-023", "catalog-024", "catalog-028", "catalog-037", "catalog-039",
    "hygiene-002", "hygiene-005", "vectors-005", "vectors-021", "vectors-025",
]


@pytest.mark.parametrize("prefix", BEAD_COMMENT_CHANGELOGS)
def test_changelogs_named_in_the_plan_audit_residual_are_inventoried(pinned: dict, prefix: str) -> None:
    """nexus-3wh8d.6's comment (plan audit r1 residual a): these carry ON CONFLICT targets
    and must each appear. catalog-023, -024 and -028 write the retired chunks_<dim> tables,
    so they appear through their other references and through the ``definitions`` history of
    the functions they first defined."""
    direct = [r for r in pinned["rows"] if r["file"].rsplit("/", 1)[-1].startswith(prefix)]
    via_history = [r for r in pinned["rows"] if r["kind"] == "function"
                   and any(d.startswith(prefix) for d in r.get("definitions", []))]
    assert direct or via_history, prefix
    if prefix not in ("catalog-023", "catalog-024", "catalog-028"):
        assert any(s.get("conflict") for r in direct for s in r["sites"]), prefix


def test_every_technical_design_row_is_used_or_documented_empty(pinned: dict) -> None:
    used = {t for r in pinned["rows"] for t in _td_ids(r)}
    # X3 is the escape hatch for a reference with no category; it must stay empty so a
    # new kind of reference gets a mapping instead of landing there silently.
    assert "X3" not in used, [r["id"] for r in pinned["rows"] if r["rdr_row"] == "X3"]
    expected = {t["id"] for t in pinned["td_rows"]} - {"X3"}
    assert expected <= used, sorted(expected - used)


def test_runalways_changesets_are_never_classified_historical(pinned: dict) -> None:
    """A runAlways changeset re-runs on every walk, including the first one after the
    migration, so its SQL runs against the NEW layout."""
    for r in pinned["rows"]:
        if r["source"] == "changelog" and r["run_always"] and r["kind"] in ("do-block", "dml"):
            assert r["rdr_row"] != "X2", r["id"]


# ---------------------------------------------------------------------------
# The guard fails when an object is added that the pinned inventory does not list
# ---------------------------------------------------------------------------

PLANT_MASTER_LINE = '    <include file="db/changelog/zz-rdr225-plant.xml"/>\n'


@pytest.fixture()
def tree_copy(tmp_path: Path, real: inv.Roots) -> inv.Roots:
    cl = tmp_path / "changelog"
    java = tmp_path / "java"
    shutil.copytree(real.changelog_dir, cl)
    shutil.copytree(real.java_dir, java)
    return inv.Roots(repo=real.repo, changelog_dir=cl, java_dir=java, anchors=real.anchors)


def test_an_untouched_copy_of_the_tree_passes(tree_copy: inv.Roots, pinned: dict) -> None:
    """Non-vacuity of the failing cases below: the same copy, unmodified, is clean."""
    assert inv.problems(tree_copy, pinned) == []


def test_a_changeset_naming_a_table_that_the_inventory_does_not_list_fails(tree_copy: inv.Roots, pinned: dict) -> None:
    body = "".join(
        f'<changeSet id="plant-{t}" author="plant"><sql>SELECT count(*) FROM nexus.{t};</sql></changeSet>\n'
        for t in inv.TABLES
    )
    (tree_copy.changelog_dir / "zz-rdr225-plant.xml").write_text(
        '<?xml version="1.0"?><databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog">\n'
        + body + "</databaseChangeLog>\n", encoding="utf-8"
    )
    master = tree_copy.changelog_dir / "db.changelog-master.xml"
    master.write_text(master.read_text(encoding="utf-8").replace("</databaseChangeLog>", PLANT_MASTER_LINE + "</databaseChangeLog>"),
                      encoding="utf-8")
    problems = inv.problems(tree_copy, pinned)
    for t in inv.TABLES:
        cs = f"zz-rdr225-plant.xml#plant-{t}"
        assert any("NEW in this tree" in p and cs in p for p in problems), (t, problems[:5])
        assert any("NOT COVERED" in p and cs in p for p in problems), (t, problems[:5])


def test_a_java_method_naming_a_table_that_the_inventory_does_not_list_fails(tree_copy: inv.Roots, pinned: dict) -> None:
    methods = "".join(
        f'    void plant_{t}(Object c) {{ c.execute("DELETE FROM nexus.{t} WHERE true"); }}\n' for t in inv.TABLES
    )
    (tree_copy.java_dir / "dev/nexus/service/RdrPlant.java").write_text(
        "package dev.nexus.service;\npublic class RdrPlant {\n" + methods + "}\n", encoding="utf-8"
    )
    problems = inv.problems(tree_copy, pinned)
    for t in inv.TABLES:
        assert any("NEW in this tree" in p and f"RdrPlant/plant_{t}" in p for p in problems), (t, problems[:5])
    assert any("NOT COVERED" in p and "java:dev/nexus/service/RdrPlant.java" in p for p in problems)


def test_a_typed_jooq_writer_added_to_an_already_listed_file_fails(tree_copy: inv.Roots, pinned: dict) -> None:
    """The crude detector is file-grained for Java, so a new method in a file that is
    already listed is caught by the row-level comparison, including typed jOOQ forms."""
    path = tree_copy.java_dir / "dev/nexus/service/db/TaxonomyRepository.java"
    text = path.read_text(encoding="utf-8")
    idx = text.rindex("}")
    path.write_text(text[:idx] + "\n    void rdrPlantedWriter(org.jooq.DSLContext ctx) {\n"
                    "        ctx.insertInto(TOPIC_ASSIGNMENTS, TOPIC_ASSIGNMENTS.TENANT_ID).values(\"t\")"
                    ".onConflict(TOPIC_ASSIGNMENTS.TENANT_ID).doNothing().execute();\n    }\n}\n", encoding="utf-8")
    problems = inv.problems(tree_copy, pinned)
    assert any("TaxonomyRepository/rdrPlantedWriter" in p for p in problems), problems[:5]


def test_changing_an_on_conflict_target_in_a_live_function_fails(tree_copy: inv.Roots, pinned: dict) -> None:
    path = tree_copy.changelog_dir / "catalog-043-gc-restore-rereferenced-live-origin-wins.xml"
    text = path.read_text(encoding="utf-8")
    assert "ON CONFLICT (tenant_id, collection, chash) DO NOTHING" in text
    path.write_text(text.replace("ON CONFLICT (tenant_id, collection, chash) DO NOTHING",
                                 "ON CONFLICT (tenant_id, collection, chash, embedding_model) DO NOTHING"), encoding="utf-8")
    problems = inv.problems(tree_copy, pinned)
    assert any("catalog-043-gc-restore-rereferenced-live-origin-wins.xml#catalog-043-" in p and "CHANGED" in p
               for p in problems), problems[:5]


def test_superseding_a_function_body_without_naming_the_tables_changes_the_inventory(tree_copy: inv.Roots, pinned: dict) -> None:
    """A later CREATE OR REPLACE that does not name the tables still supersedes the
    live body the inventory records, so it must show up."""
    (tree_copy.changelog_dir / "zz-rdr225-plant.xml").write_text(
        '<?xml version="1.0"?><databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog">'
        '<changeSet id="plant-supersede" author="plant"><sql splitStatements="false">'
        "CREATE OR REPLACE FUNCTION nexus.reaper_quarantine_chunks(a text, b text, c text, d text, e text, "
        "f text, g text, h text, i text) RETURNS void LANGUAGE sql AS $$ SELECT 1 $$;"
        "</sql></changeSet></databaseChangeLog>\n", encoding="utf-8"
    )
    master = tree_copy.changelog_dir / "db.changelog-master.xml"
    master.write_text(master.read_text(encoding="utf-8").replace("</databaseChangeLog>", PLANT_MASTER_LINE + "</databaseChangeLog>"),
                      encoding="utf-8")
    problems = inv.problems(tree_copy, pinned)
    assert any("reaper_quarantine_chunks" in p and "CHANGED" in p for p in problems), problems[:5]


# ---------------------------------------------------------------------------
# Blind spots closed in the fix round: each is a plant on the tree copy that must fail
# ---------------------------------------------------------------------------


def _plant_changeset(tree: inv.Roots, cs_id: str, inner: str) -> None:
    (tree.changelog_dir / "zz-rdr225-plant.xml").write_text(
        '<?xml version="1.0"?><databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog">'
        f'<changeSet id="{cs_id}" author="plant">{inner}</changeSet></databaseChangeLog>\n',
        encoding="utf-8")
    master = tree.changelog_dir / "db.changelog-master.xml"
    master.write_text(master.read_text(encoding="utf-8").replace(
        "</databaseChangeLog>", PLANT_MASTER_LINE + "</databaseChangeLog>"), encoding="utf-8")


@pytest.mark.parametrize("spelling", ['nexus."chunks"', '"nexus"."chunks"', '"chunks"'])
def test_a_changeset_naming_a_table_in_quotes_fails(tree_copy: inv.Roots, pinned: dict, spelling: str) -> None:
    _plant_changeset(tree_copy, "plant-quoted", f"<sql>SELECT count(*) FROM {spelling};</sql>")
    problems = inv.problems(tree_copy, pinned)
    assert any("NEW in this tree" in p and "plant-quoted" in p for p in problems), problems[:5]
    assert any("NOT COVERED" in p and "plant-quoted" in p for p in problems), problems[:5]


@pytest.mark.parametrize("inner", [
    '<addColumn tableName="chunks"><column name="embedding_model" type="text"/></addColumn>',
    '<createIndex tableName="topic_assignments" indexName="plant_idx"><column name="a"/></createIndex>',
    '<sqlFile path="plant.sql" relativeToChangelogFile="true"/>',
    '<customChange class="dev.nexus.Plant"/>',
])
def test_a_native_change_element_added_to_the_tree_fails(tree_copy: inv.Roots, pinned: dict, inner: str) -> None:
    _plant_changeset(tree_copy, "plant-native", inner)
    problems = inv.problems(tree_copy, pinned)
    assert any(p.startswith("UNSCANNABLE") and "plant-native" in p for p in problems), problems[:5]


def test_a_jooq_record_class_added_to_an_already_listed_file_fails(tree_copy: inv.Roots, pinned: dict) -> None:
    path = tree_copy.java_dir / "dev/nexus/service/db/TaxonomyRepository.java"
    text = path.read_text(encoding="utf-8")
    idx = text.rindex("}")
    path.write_text(text[:idx] + "\n    void rdrPlantedRecord() {\n"
                    "        TopicAssignmentsRecord rec = new TopicAssignmentsRecord();\n        rec.store();\n    }\n}\n",
                    encoding="utf-8")
    problems = inv.problems(tree_copy, pinned)
    assert any("TaxonomyRepository/rdrPlantedRecord" in p for p in problems), problems[:5]


def test_the_real_tree_has_nothing_the_scanner_cannot_read(real: inv.Roots, pinned: dict) -> None:
    """The pinned file records an EMPTY unscannable list, and the key must exist: a pinned file
    from before the guard would otherwise pass this by default."""
    assert pinned["unscannable"] == []
    assert inv.unscannable(real) == []


def test_generation_over_the_real_tree_is_byte_identical_across_hash_seeds(tmp_path: Path) -> None:
    outs = []
    for seed in ("1", "2"):
        out = tmp_path / f"seed-{seed}.json"
        env = {**os.environ, "PYTHONHASHSEED": seed}
        subprocess.run([sys.executable, str(Path(inv.__file__).resolve()), "--write", "--pinned", str(out),
                        "--source-sha", "fixed"], env=env, check=True, capture_output=True, timeout=300)
        outs.append(out.read_bytes())
    assert outs[0] and outs[0] == outs[1]


def test_python_registries_are_recorded_entry_by_entry(pinned: dict) -> None:
    """Cross-checked against the standard-library syntax tree, an independent reader of the same
    literal: the container row holds exactly the entries the tuple has, and every entry that
    names a table is a row of its own."""
    rows = {r["id"]: r for r in pinned["rows"] if r["source"] == "python"}
    tree = ast.parse((inv.REPO_ROOT / "src/nexus/health.py").read_text(encoding="utf-8"))
    (rls,) = [n for n in ast.walk(tree)
              if isinstance(n, ast.AnnAssign) and getattr(n.target, "id", "") == "_RLS_TENANT_TABLES"]
    expected = [e.value for e in rls.value.elts]
    container = rows["python:src/nexus/health.py#_RLS_TENANT_TABLES"]
    assert [e.strip('"') for e in container["entries"]] == expected
    for table in inv.TABLES:
        assert f"python:src/nexus/health.py#_RLS_TENANT_TABLES:nexus.{table}" in rows, table
    # a registry the first version missed: the pre-unify list names catalog_document_chunks too
    assert "python:src/nexus/db/chash_tables.py#LEGACY_CHASH_BEARING_TABLES:nexus.catalog_document_chunks" in rows
    assert "python:src/nexus/db/chash_tables.py#CHASH_BEARING_TABLES:nexus.catalog_document_chunks" in rows
    assert "python:src/nexus/db/chash_tables.py#CHASH_BEARING_TABLES:CHUNKS_TABLE" in rows
