# SPDX-License-Identifier: AGPL-3.0-or-later
"""nx agents install worktree-developer (nexus-uympf): the user-scope agent is
COMPOSED from the sn template and the conexus developer, never hand-copied."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import click
import pytest
from click.testing import CliRunner

from nexus import health
from nexus.commands import agents_cmd
from nexus.commands.agents_cmd import agents_group, compose_worktree_developer, installed_plugin_dir, worktree_developer_drift

REPO_ROOT = Path(__file__).parent.parent
SN_DIR = REPO_ROOT / "sn"
CONEXUS_DIR = REPO_ROOT / "conexus"
TEMPLATE = SN_DIR / "examples" / "worktree-developer.md"
DEVELOPER = CONEXUS_DIR / "agents" / "developer.md"


def _run(*args: str) -> tuple[int, str]:
    result = CliRunner().invoke(agents_group, ["install", "worktree-developer", "--sn-dir", str(SN_DIR), "--conexus-dir", str(CONEXUS_DIR), *args])
    return result.exit_code, result.output


@pytest.fixture
def composed() -> str:
    return compose_worktree_developer(sn_dir=SN_DIR, conexus_dir=CONEXUS_DIR)


class TestCompose:
    def test_frontmatter_keeps_the_private_server_and_inherits_developer_tuning(self, composed: str) -> None:
        fm = composed.split("\n---\n", 1)[0]
        template_fm = TEMPLATE.read_text().split("\n---\n", 1)[0]
        assert fm.startswith("---\nname: worktree-developer\n")
        assert "serena-wt:" in fm and "plugin_sn_serena" not in fm
        assert "--project-from-cwd" not in fm
        for key in ("model:", "color:", "effort:"):
            assert key in fm, key
            assert key not in template_fm, "template now sets it; drop the inheritance assertion"
        assert fm.index("model:") < fm.index("mcpServers:"), "scalar keys precede the mcpServers block"
        assert fm.count("\nname:") == 1, "the developer's name must not leak in"

    def test_body_is_preamble_then_developer_verbatim(self, composed: str) -> None:
        body = composed.split("\n---\n", 1)[1]
        assert body.startswith("<!-- generated by `nx agents install worktree-developer`")
        preamble = TEMPLATE.read_text().split("\n---\n", 1)[1].strip("\n")
        assert preamble in body
        developer_body = DEVELOPER.read_text().split("\n---\n", 1)[1]
        for heading in ("## Pre-flight", "## Post-flight", "## Circuit Breaker", "## Completion Protocol"):
            assert heading in developer_body and heading in body, heading
        assert body.index("activate_project") < body.index("## Pre-flight"), "activation comes before the method"
        # Everything of the developer body survives except the rewritten links.
        stripped = developer_body.replace("./_shared/", "")
        assert stripped.strip("\n") in body.replace((CONEXUS_DIR / "agents" / "_shared").as_posix() + "/", "")

    def test_shared_links_resolve_from_the_agents_dir(self, composed: str) -> None:
        assert "](./_shared/" not in composed
        shared = CONEXUS_DIR / "agents" / "_shared"
        assert f"]({shared.as_posix()}/CONTEXT_PROTOCOL.md" in composed
        assert (shared / "CONTEXT_PROTOCOL.md").is_file()

    def test_header_names_both_source_versions(self, tmp_path: Path) -> None:
        """Each slot reads its OWN plugin.json: two distinct versions must both appear in order."""
        sn = tmp_path / "sn"; cx = tmp_path / "conexus"
        shutil.copytree(SN_DIR / "examples", sn / "examples")
        (sn / ".claude-plugin").mkdir(); (sn / ".claude-plugin" / "plugin.json").write_text('{"version": "1.2.3"}')
        (cx / "agents").mkdir(parents=True); shutil.copy(DEVELOPER, cx / "agents" / "developer.md")
        (cx / ".claude-plugin").mkdir(); (cx / ".claude-plugin" / "plugin.json").write_text('{"version": "4.5.6"}')
        composed = compose_worktree_developer(sn_dir=sn, conexus_dir=cx)
        assert "from sn 1.2.3 + conexus 4.5.6;" in composed

    def test_relative_conexus_dir_yields_absolute_shared_links(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.chdir(REPO_ROOT)
        composed = compose_worktree_developer(sn_dir=Path("sn"), conexus_dir=Path("conexus"))
        assert f"]({(REPO_ROOT / 'conexus' / 'agents' / '_shared').resolve().as_posix()}/" in composed
        assert "](conexus/agents/_shared" not in composed

    def test_bad_template_frontmatter_is_a_click_error(self, tmp_path: Path) -> None:
        sn = tmp_path / "sn"
        (sn / "examples").mkdir(parents=True)
        (sn / "examples" / "worktree-developer.md").write_text("---\n- just: a list\n---\nbody\n")
        with pytest.raises(click.ClickException, match="not a mapping"):
            compose_worktree_developer(sn_dir=sn, conexus_dir=CONEXUS_DIR)

    def test_missing_input_is_a_click_error(self, tmp_path: Path) -> None:
        with pytest.raises(click.ClickException, match="missing input"):
            compose_worktree_developer(sn_dir=tmp_path, conexus_dir=CONEXUS_DIR)


class TestInstall:
    def test_write_then_check_is_clean_then_drift_is_reported(self, tmp_path: Path) -> None:
        dest = tmp_path / "agents" / "worktree-developer.md"
        code, out = _run("--dest", str(dest))
        assert code == 0 and "wrote" in out and dest.is_file()
        code, out = _run("--dest", str(dest), "--check")
        assert code == 0 and "up to date" in out
        code, out = _run("--dest", str(dest))
        assert code == 0 and "already up to date" in out
        dest.write_text(dest.read_text() + "\nlocal edit\n")
        code, out = _run("--dest", str(dest), "--check")
        assert code == 1 and "differs" in out and "nx agents install worktree-developer" in out
        code, out = _run("--dest", str(dest))
        assert code == 0 and "updated" in out
        assert dest.read_text() == compose_worktree_developer(sn_dir=SN_DIR, conexus_dir=CONEXUS_DIR)

    def test_check_on_missing_file_exits_one_and_writes_nothing(self, tmp_path: Path) -> None:
        dest = tmp_path / "worktree-developer.md"
        code, out = _run("--dest", str(dest), "--check")
        assert code == 1 and "missing" in out and not dest.exists()

    def test_check_and_dry_run_are_exclusive(self, tmp_path: Path) -> None:
        code, out = _run("--dest", str(tmp_path / "x.md"), "--check", "--dry-run")
        assert code == 2 and "mutually exclusive" in out

    def test_dry_run_prints_without_writing(self, tmp_path: Path) -> None:
        dest = tmp_path / "worktree-developer.md"
        code, out = _run("--dest", str(dest), "--dry-run")
        assert code == 0 and out.startswith("---\nname: worktree-developer\n") and not dest.exists()


class TestInstalledPluginDir:
    def test_reads_claude_code_manifest(self, tmp_path: Path) -> None:
        plugin = tmp_path / "cache" / "sn" / "9.9.9"
        plugin.mkdir(parents=True)
        manifest = tmp_path / "installed_plugins.json"
        manifest.write_text(json.dumps({"version": 2, "plugins": {"sn@nexus-plugins": [{"installPath": str(plugin)}]}}))
        assert installed_plugin_dir("sn", manifest=manifest) == plugin

    @pytest.mark.parametrize("payload", [None, "{not json", "[]", json.dumps({"plugins": {}}), json.dumps({"plugins": {"sn@nexus-plugins": [{"installPath": "/nowhere/sn"}]}})])
    def test_missing_corrupt_or_pluginless_manifest_names_the_fix(self, tmp_path: Path, payload: str | None) -> None:
        manifest = tmp_path / "installed_plugins.json"
        if payload is not None:
            manifest.write_text(payload)
        with pytest.raises(click.ClickException, match="sn@nexus-plugins|--sn-dir"):
            installed_plugin_dir("sn", manifest=manifest)


class TestDoctorDrift:
    """worktree_developer_drift feeds nx doctor's _check_worktree_developer_agent (critique finding 2)."""

    def _manifest(self, tmp_path: Path) -> Path:
        manifest = tmp_path / "installed_plugins.json"
        manifest.write_text(json.dumps({"plugins": {
            "sn@nexus-plugins": [{"installPath": str(SN_DIR)}],
            "conexus@nexus-plugins": [{"installPath": str(CONEXUS_DIR)}],
        }}))
        return manifest

    def test_absent_agent_is_silent(self, tmp_path: Path) -> None:
        assert worktree_developer_drift(dest=tmp_path / "none.md", manifest=self._manifest(tmp_path)) is None

    def test_current_agent_is_silent_and_stale_agent_is_named(self, tmp_path: Path) -> None:
        manifest = self._manifest(tmp_path)
        dest = tmp_path / "worktree-developer.md"
        dest.write_text(compose_worktree_developer(sn_dir=SN_DIR, conexus_dir=CONEXUS_DIR))
        assert worktree_developer_drift(dest=dest, manifest=manifest) is None
        dest.write_text("stale\n")
        assert "differs from the installed plugins" in (worktree_developer_drift(dest=dest, manifest=manifest) or "")

    def test_uninstalled_plugins_are_reported_not_raised(self, tmp_path: Path) -> None:
        dest = tmp_path / "worktree-developer.md"
        dest.write_text("whatever\n")
        problem = worktree_developer_drift(dest=dest, manifest=tmp_path / "missing.json")
        assert problem is not None and "cannot recompose" in problem

    def test_doctor_check_surfaces_a_warning(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        dest = tmp_path / "worktree-developer.md"
        dest.write_text("stale\n")
        monkeypatch.setattr(agents_cmd, "worktree_developer_drift",
                            lambda **_: f"{dest} differs from the installed plugins")
        results = health._check_worktree_developer_agent()
        assert len(results) == 1 and results[0].warn and not results[0].ok and not results[0].fatal
        assert results[0].fix_suggestions == ["nx agents install worktree-developer"]
        monkeypatch.setattr(agents_cmd, "worktree_developer_drift", lambda **_: None)
        assert health._check_worktree_developer_agent() == []
