# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Hal Hildebrand. All rights reserved.
"""Write the nexus-owned shims that bind a spawn to the current generation.

nexus-utpuw.4 (P1c), collapsed out of ``shims.sh``. Stdlib-only and importing
nothing from nexus, for the reason ``layout_core``, ``census_core`` and
``gc_core`` are: ``shims.sh`` dispatches here and is sourced by the installer
and by ``scripts/reinstall-tool.sh``, which run with NOTHING installed and
cannot import nexus. Pinned by
``tests/test_install_shims_core_is_bootstrap_safe.py``.

THE SET IS DERIVED, NOT LISTED. Audit finding F1: a hardcoded five-name
allowlist omitted ``nx-session-end-launcher``, the fourth console script, which
``conexus/hooks/hooks.json`` invokes by bare PATH name with no fallback. So

    shim set = the installed distribution's own console scripts
             ∪ layout_core.DEPENDENCY_SCRIPTS

the first clause asked of the generation itself, so a fifth script needs no
edit here. It stays an EXCLUSION discipline and never a glob over
``<gen>/bin``, because that directory also holds python, pip and activate.

ONE OWNED SET, ASKED ONCE
=========================
The writer and the pruner must agree on which names are ours, and the shell
half did not: ``shims.sh`` recomputed the owned set inline in its prune loop
while ``layout_core.owned_shim_names`` computed it for ``nx doctor`` and for
``self_cmd``'s reclaim repair. Its own comment said "the two must agree or the
twins drift", which is the drift that a second copy always eventually does.

MEASURED before this file existed, by running the shell writer against a
generation declaring a hostile entry point that also exists in ``bin/``:

    kept by the shell's prune : ['nx', 'nx$(touch${IFS}PWNED)']
    owned_shim_names          : ['nx']

The shell's inline rule never consulted the name allowlist, so a hostile name
was OWNED by the pruner and therefore kept forever, while the writer refused to
write it and ``nx doctor``'s ``_check_shims_match_template`` -- which walks the
owned set -- never looked at it. That combination is why nothing noticed: the
one component that would have removed such a file was the one component that
believed it belonged there. It is reachable from history rather than
hypothetical, because the pre-nexus-xk7g2 writer used a DENYLIST that admitted
exactly that name, and the body it rendered interpolated the name into a script
placed on the operator's PATH.

Here the two cannot disagree: the declared set is fetched ONCE, and both the
write list and the prune's owned set come from ``owned_from_declared`` -- the
same function ``owned_shim_names`` calls. Asking twice would also be two
subprocess reads of the generation's metadata, which can differ.

ENTRY POINTS ARE THIRD-PARTY DATA. They come from whatever wheels the
distribution depends on, so a name arriving here is not ours, and it is
interpolated into a shell script written onto the operator's PATH.
``declared_console_scripts`` runs the layout contract's ALLOWLIST over every
name and says out loud which it refused; nexus-xk7g2 is why that is an
allowlist and not a denylist. A refused name is SKIPPED WITH A WARNING and
never written -- silence would leave an operator whose tool vanished with
nothing to read.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

#: EX_USAGE. The same status ``layout_core`` refuses with, and the shell half's
#: ``NX_LAYOUT_USAGE_EXIT``. Restated rather than imported from the sibling so
#: that a refusal path does not depend on the sibling loading; pinned equal by
#: ``tests/test_install_shims_twins_agree.py``.
SHIMS_USAGE_EXIT = 64

#: The first line of every shim body after the shebang, and the marker the
#: prune matches on. Content rather than a name list, the same exclusion
#: discipline F1 and nexus-xk7g2 forced on the writer: the bin dir also holds
#: tools nexus does not own.
SHIM_MARKER = "# Generated by nexus."

_LAYOUT = None


def _sibling(name: str):
    """A neighbour module in ``_install/``, as ONE object per process.

    Two worlds, and the rule differs between them:

    * Imported as part of the package, ``__package__`` is ``nexus._install``
      and the package sibling IS the adjacent file, so it is imported
      normally. That keeps ONE module object per process, which matters for
      more than tidiness: ``LayoutError`` must be one class or
      ``except InstallLayoutError`` stops catching errors raised in here, and
      a test patching ``nexus._install.layout_core`` must reach this caller.
    * Run as a script at bootstrap there is no package, so the file is loaded
      by path under a stable key and REUSED from ``sys.modules`` on the next
      ask.

    Pinned by ``tests/test_install_cores_share_one_module_identity.py``.
    """
    if __package__:
        from importlib import import_module  # noqa: PLC0415 -- package world only

        return import_module(f"{__package__}.{name}")

    key = f"_nx_install_{name}"
    cached = sys.modules.get(key)
    if cached is not None:
        return cached

    import importlib.util  # noqa: PLC0415 -- bootstrap path only

    path = Path(__file__).resolve().parent / f"{name}.py"
    spec = importlib.util.spec_from_file_location(key, path)
    if spec is None or spec.loader is None:  # pragma: no cover -- unreachable
        raise ImportError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    # Registered BEFORE exec, so a sibling that reaches back mid-import finds
    # the partially-built module rather than starting a second load of it.
    sys.modules[key] = module
    spec.loader.exec_module(module)
    return module


def _layout():
    global _LAYOUT
    if _LAYOUT is None:
        _LAYOUT = _sibling("layout_core")
    return _LAYOUT


class ShimsError(Exception):
    """The writer refuses to proceed. Raised before anything is written."""


def _write_one(bin_dir: Path, name: str, body: str) -> None:
    """Per-file atomic.

    A reader on PATH sees the old shim or the new one, never a half-written
    script. The replace also REPLACES a uv-owned symlink at this name rather
    than following it into the old target, which is what migration (.7)
    depends on.
    """
    tmp = bin_dir / f".{name}.tmp.{os.getpid()}"
    tmp.write_text(body)
    tmp.chmod(0o755)
    os.replace(tmp, bin_dir / name)


def _is_ours(path: Path, pointer: Path) -> bool:
    """Whether this file is a shim THIS install wrote.

    Two guards, both required. The content marker keeps us to our own files --
    the bin dir also holds tools nexus does not own. The pointer path keeps us
    to OUR install's files, so an unrelated nexus sharing this bin dir keeps
    its own shims.

    A symlink is deliberately never ours: our shims are always regular files,
    so a symlink at a shim's name is uv's, and ``self_cmd``'s reclaimed-shims
    repair owns that case. We also cannot read a broken symlink to prove it is
    ours, and refusing to delete what we cannot identify is the right default
    in a directory we do not own outright.
    """
    if not path.is_file() or path.is_symlink():
        return False
    try:
        text = path.read_text(errors="replace")
    except OSError:
        return False
    first = text.split("\n", 2)
    if not any(line.startswith(SHIM_MARKER) for line in first):
        return False
    return str(pointer) in text


def write_shims(
    generation: Path | str,
    bin_dir: Path | str | None = None,
    dist: str = "conexus",
) -> list[str]:
    """Write every shim *generation* should own, then prune what it should not.

    Returns the diagnostics the caller should show; writing them is the CLI's
    job, so a test can assert on the list rather than scrape stderr.

    Raises :class:`ShimsError` for every refusal, all of them BEFORE any file
    is written: a partial shim set is worse than none, because the operator
    sees mineru appear and nx quietly vanish.
    """
    layout = _layout()
    gen = Path(generation)
    if not gen.is_absolute():
        raise ShimsError(f"generation must be an absolute path, got '{generation}'")
    if not gen.is_dir():
        raise ShimsError(f"generation is not a directory: {gen}")

    target = Path(bin_dir) if bin_dir else layout.bin_dir()

    # The lookup's failure is CHECKED and refuses the WHOLE set. Without this
    # the dependency scripts would still be written and the run would report
    # success. declared_console_scripts raises LayoutError for "could not ask"
    # AND for "declares nothing", so a dist-name mismatch can never silently
    # unshim every one of the project's own console scripts (RG-A).
    # The DETAIL form, because this is a dispatch: its stdout is reserved for
    # results, and the warning form routes to structlog whenever structlog
    # imports, which in an installed venv prints to stdout. The refused names
    # come back as data and are placed on stderr below.
    try:
        declared, refused = layout.declared_console_scripts_detail(gen, dist)
    except Exception as exc:
        raise ShimsError(
            f"could not read console scripts from distribution '{dist}' in {gen} "
            f"— refusing to write a partial shim set: {exc}"
        ) from exc

    # ONE owned set for both phases; see the module docstring.
    owned = layout.owned_from_declared(declared, gen)

    target.mkdir(parents=True, exist_ok=True)

    diagnostics: list[str] = [
        # Never silently dropped: an operator whose tool vanished has to have
        # something to read. The name is quoted because the ones that get here
        # contain spaces and shell metacharacters by definition.
        f"nexus: refused console script {name!r} from distribution '{dist}' "
        "— its name is not a valid shim command, so no shim was written"
        for name in refused
    ]
    for name in sorted(owned):
        # VALIDATION LIVES IN THE CONTRACT and there is no second copy here.
        # declared_console_scripts already ran the allowlist and said which
        # names it refused; render_shim runs it again on the way into the body.
        # An earlier version of the shell half ALSO checked the allowlist
        # itself, and that branch was unreachable: deleting it left every test
        # green. A duplicated guard no test can distinguish is not defence in
        # depth, it is a second thing to keep in sync that reads as protection.
        try:
            body = layout.render_shim(name, tools=gen.parent)
        except layout.LayoutError as exc:
            # The renderer refuses and names what it refused. Caught NARROWLY,
            # by the sibling's own error class rather than by Exception:
            # anything else coming out of render_shim is a defect, and
            # swallowing it here would turn it into a silently missing shim --
            # the failure mode this whole file exists to make loud.
            diagnostics.append(f"nexus: skipped shim '{name}': {exc}")
            continue
        _write_one(target, name, body)

    diagnostics.extend(_prune(target, gen, owned))
    return diagnostics


def _prune(bin_dir: Path, generation: Path, owned: frozenset[str] | set[str]) -> list[str]:
    """Remove shims THIS generation no longer owns (nexus-3z8vb).

    Writing is not enough. A console script that LEAVES the distribution keeps
    the shim an earlier generation wrote, and that shim still resolves
    ``current`` and then execs a path that is gone::

        nx-hook: line 15: <gen>/bin/nx-hook: No such file or directory

    Measured on a real box: gen A shipped bin/nx-hook, gen B (the released
    7.54.0, cut while that console script was deferred) did not, and the shim
    from A survived the flip pointing into B.

    This is WORSE than a missing shim, which is why it is pruned rather than
    tolerated: ``command -v nx-hook`` SUCCEEDS and so does ``test -x``, so
    every presence probe reports healthy and the failure appears only at exec,
    complaining about the TARGET rather than about the install. The writer
    already refuses to CREATE that shape; this removes the same shape when it
    arrives from history instead of from this run.

    A failure to remove one file does NOT abort. The write phase has already
    succeeded and ``current`` may already point at this generation, so turning
    one unremovable file into a raised error would fail an entire
    ``nx self install`` over a stale shim that is merely still present.
    """
    layout = _layout()
    pointer = generation.parent / layout.CURRENT_LINK_NAME
    diagnostics: list[str] = []
    try:
        entries = sorted(bin_dir.iterdir())
    except OSError:
        return diagnostics
    for found in entries:
        if found.name in owned:
            continue
        if not _is_ours(found, pointer):
            continue
        try:
            found.unlink()
        except OSError:
            diagnostics.append(
                f"nexus: could not remove stale shim '{found}' — remove it by hand; "
                "it resolves but cannot exec"
            )
        else:
            diagnostics.append(
                f"nexus: removed stale shim '{found.name}' — this generation "
                "ships no such program"
            )
    return diagnostics


# ---------------------------------------------------------------------------
# The command-line face, for shims.sh
#
# shims.sh dispatches here rather than restating any of this. The calling
# contract is the shell half's own: results on STDOUT and nothing else there,
# refusals on STDERR with an empty stdout and SHIMS_USAGE_EXIT.
#
# write_shims prints NOTHING to stdout even on success. Its product is files,
# and its diagnostics are diagnostics: a caller writing
# `nx_write_shims "$gen" "$bin"` reads the exit status, and a line on stdout
# there is a line some caller will eventually capture and treat as a path.
# ---------------------------------------------------------------------------


def _cli_write(generation: str, bin_dir: str = "", dist: str = "conexus") -> None:
    for line in write_shims(generation, bin_dir or None, dist or "conexus"):
        sys.stderr.write(line + "\n")


_VERBS = {"write": _cli_write}


def main(argv: list[str]) -> int:
    """Run one verb. Returns the process exit status."""
    if not argv:
        sys.stderr.write("nexus: shims_core: no verb given\n")
        return SHIMS_USAGE_EXIT
    verb, args = argv[0], argv[1:]
    fn = _VERBS.get(verb)
    if fn is None:
        known = ", ".join(sorted(_VERBS))
        sys.stderr.write(f"nexus: shims_core: unknown verb {verb!r}; known: {known}\n")
        return SHIMS_USAGE_EXIT
    try:
        fn(*args)
    except ShimsError as exc:
        sys.stderr.write(f"nexus: {exc}\n")
        return SHIMS_USAGE_EXIT
    except TypeError as exc:
        sys.stderr.write(f"nexus: shims_core: bad arguments to {verb}: {exc}\n")
        return SHIMS_USAGE_EXIT
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
