#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Committed listing of the native resources the engine's embedding jars ship (nexus-zz2w7).

The native build embeds onnxruntime's and DJL tokenizers' per-platform native
libraries through ``-H:IncludeResources`` patterns in service/pom.xml, and
``scripts/check_native_embedded_resources.py`` requires a per-platform library
list. Both are pinned against ``tests/fixtures/native_jar_listings.txt``, which
this script generates from the real jars in the local Maven repository, so CI
needs no ``~/.m2``.

Regenerate after bumping ``onnxruntime.version`` or ``djl.tokenizers.version``
in service/pom.xml (the tests fail until you do):

    uv run python scripts/native_jar_listing.py --write

``--check`` exits 1 when the committed file differs from the jars (use it
where ``~/.m2`` has the jars; it fails loudly, never skips, when they are
absent).
"""
from __future__ import annotations

import argparse
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
POM = ROOT / "service" / "pom.xml"
LISTING = ROOT / "tests" / "fixtures" / "native_jar_listings.txt"
NS = {"m": "http://maven.apache.org/POM/4.0.0"}

# (groupId, artifactId, pom property holding the version, resource prefix listed)
JARS = (
    ("com.microsoft.onnxruntime", "onnxruntime", "onnxruntime.version", "ai/onnxruntime/native/"),
    ("ai.djl.huggingface", "tokenizers", "djl.tokenizers.version", "native/lib/"),
)


def pom_property(name: str) -> str:
    root = ET.parse(POM).getroot()
    value = root.findtext(f"./m:properties/m:{name}", namespaces=NS)
    if not value:
        raise SystemExit(f"{POM}: property {name} not found")
    return value.strip()


def jar_path(m2: Path, group: str, artifact: str, version: str) -> Path:
    return m2 / group.replace(".", "/") / artifact / version / f"{artifact}-{version}.jar"


def render(m2: Path) -> str:
    lines = [
        "# Generated by scripts/native_jar_listing.py --write; do not edit by hand.",
        "# One section per jar: '# jar <group>:<artifact>:<version> <prefix>', then every",
        "# non-directory, non-.class entry under <prefix>, sorted.",
    ]
    for group, artifact, prop, prefix in JARS:
        version = pom_property(prop)
        path = jar_path(m2, group, artifact, version)
        if not path.is_file():
            raise SystemExit(f"jar not found: {path} (run ./mvnw dependency:resolve in service/)")
        with zipfile.ZipFile(path) as jar:
            names = sorted(
                n for n in jar.namelist()
                if n.startswith(prefix) and not n.endswith("/") and not n.endswith(".class")
            )
        if not names:
            raise SystemExit(f"{path}: no entries under {prefix}; the jar layout changed")
        lines.append(f"# jar {group}:{artifact}:{version} {prefix}")
        lines.extend(names)
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite the committed listing")
    mode.add_argument("--check", action="store_true", help="exit 1 if the committed listing differs")
    parser.add_argument("--m2", type=Path, default=Path.home() / ".m2" / "repository")
    args = parser.parse_args(argv)
    text = render(args.m2)
    if args.write:
        LISTING.parent.mkdir(parents=True, exist_ok=True)
        LISTING.write_text(text)
        print(f"wrote {LISTING}")
        return 0
    if not LISTING.is_file() or LISTING.read_text() != text:
        print(f"{LISTING} differs from the jars; run with --write", file=sys.stderr)
        return 1
    print("native jar listing matches the jars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
