#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Regenerate ``tests/fixtures/bead_ids.txt`` from the live bead store.

The docs citation lint (``tests/test_docs_reference_rot.py``) resolves the
bead ids cited under ``docs/`` against this manifest, so the leg runs in CI,
where ``bd`` is not installed. Until 2026-09-04 that leg skipped there and
only ever ran on a developer's box (critique [24392] finding 5; Sam's
ruling: resolve from a tracked artifact). The tracked ``.beads/issues.jsonl``
is not that artifact: it is a May export of 255 rows against a Dolt store of
6,079, and it carries descriptions. This manifest is ids only, one per line,
sorted, so a refresh is a readable diff.

Freshness is checked by the lint itself where ``bd`` is present: a cited id
that is live but missing here fails with this script's name. Run it after
filing a bead you then cite in docs:

    uv run python scripts/refresh_bead_id_manifest.py
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "tests" / "fixtures" / "bead_ids.txt"


def live_bead_ids(repo_root: Path = REPO_ROOT) -> set[str]:
    """Every bead id ``bd`` knows, all statuses. Raises on any failure."""
    proc = subprocess.run(
        ["bd", "list", "--all", "--json", "--skip-labels"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=True,
    )
    return {row["id"] for row in json.loads(proc.stdout)["issues"]}


def read_manifest(path: Path = MANIFEST) -> set[str]:
    return {
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def write_manifest(ids: set[str], path: Path = MANIFEST) -> None:
    body = "\n".join(sorted(ids))
    path.write_text(
        "# Bead ids known to the live store, one per line, sorted.\n"
        "# Generated by scripts/refresh_bead_id_manifest.py; read by\n"
        "# tests/test_docs_reference_rot.py. Do not edit by hand.\n"
        f"{body}\n"
    )


def main() -> int:
    before = read_manifest() if MANIFEST.exists() else set()
    ids = live_bead_ids()
    write_manifest(ids)
    added, removed = len(ids - before), len(before - ids)
    sys.stdout.write(f"{MANIFEST.relative_to(REPO_ROOT)}: {len(ids)} ids (+{added} -{removed})\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
